// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package tinysqlstudio2.proxies.constants;

import com.mendix.core.Core;

public final class Constants
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Constants() {}

	// These are the constants for the TinySqlStudio2 module

	/**
	* 1ページに表示する件数を指定。デフォルト値は100
	* 
	* Specify the number of items to display on one page. The default value is 100
	*/
	public static java.lang.Long getDisplayCount()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("TinySqlStudio2.DisplayCount");
	}
}