// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum DatePartSelector
{
	year("486afbdb-efba-4775-b0d9-512d9ed496c7"),
	month("746d6a3e-3f05-49f2-8e80-0d0e5d1917c0"),
	day("7823b0e5-452e-45f1-826d-df20e83f2c0e");

	private final java.lang.String i18nCaptionKey;
	
	private DatePartSelector(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
