// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum LogLevel
{
	Trace("b4ab3308-2afe-4f76-982e-b0fcd2181bf7"),
	Debug("ed8460be-8bc0-4711-bee7-1ec472289edb"),
	Info("96d19d51-82e8-4fc0-a5a2-4eab3d7cc736"),
	Warning("87e67351-ba7b-4ae5-a005-56f8098f2052"),
	Error("6f375cb3-aba1-46fa-8439-0816b282b018"),
	Critical("c9e1a484-019e-4236-9c54-724128e76d02");

	private final java.lang.String i18nCaptionKey;
	
	private LogLevel(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
