// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum SanitizerPolicy
{
	BLOCKS("f23ce2a0-db45-4ea8-8c0e-bece418dd7b3"),
	FORMATTING("a6323307-66fd-41ca-8c33-3e2d95b85b43"),
	IMAGES("7b66180b-20b4-4410-bd51-5276c9e456e6"),
	LINKS("7a14ebea-e7e3-4a8a-a47c-9cd45889f076"),
	STYLES("d89484a7-16ed-41f7-aaa5-92a142caacc5"),
	TABLES("d1631553-bce3-466c-a720-d9d0c138a510");

	private final java.lang.String i18nCaptionKey;
	
	private SanitizerPolicy(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
