// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum StandardEncodings
{
	US_ASCII("4042697c-40c1-401b-b6d4-1c2bacce565b"),
	ISO_8859_1("f38dd4cc-8f3f-401d-9f6d-e23933cfa2db"),
	UTF_8("0deff931-69a5-48c7-ae70-559728e6470c"),
	UTF_16BE("5973a27d-047b-4e24-b11b-273182940191"),
	UTF_16LE("6f87df2c-eb4b-4ed1-9dc9-65e19d32d858"),
	UTF_16("525e252a-c9d3-43e1-b581-cb91994817c9");

	private final java.lang.String i18nCaptionKey;
	
	private StandardEncodings(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
