// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package twowaysql.proxies;

/**
 * Stores information for generating org.apache.commons.csv.CSVFormat
 */
public class CsvFormat implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject csvFormatMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TwoWaySQL.CsvFormat";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Delimiter("Delimiter"),
		QuoteCharacter("QuoteCharacter"),
		RecordSeparator("RecordSeparator"),
		EscapeCharacter("EscapeCharacter"),
		Trim("Trim"),
		QuoteMode("QuoteMode"),
		DateTimeFormat("DateTimeFormat"),
		ZoneId("ZoneId");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CsvFormat(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected CsvFormat(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject csvFormatMendixObject)
	{
		if (csvFormatMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!csvFormatMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.csvFormatMendixObject = csvFormatMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static twowaysql.proxies.CsvFormat initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new twowaysql.proxies.CsvFormat(context, mendixObject);
	}

	public static twowaysql.proxies.CsvFormat load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return twowaysql.proxies.CsvFormat.initialize(context, mendixObject);
	}

	/**
	 * @return value of Delimiter
	 */
	public final java.lang.String getDelimiter()
	{
		return getDelimiter(getContext());
	}

	/**
	 * @param context
	 * @return value of Delimiter
	 */
	public final java.lang.String getDelimiter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Delimiter.toString());
	}

	/**
	 * Set value of Delimiter
	 * @param delimiter
	 */
	public final void setDelimiter(java.lang.String delimiter)
	{
		setDelimiter(getContext(), delimiter);
	}

	/**
	 * Set value of Delimiter
	 * @param context
	 * @param delimiter
	 */
	public final void setDelimiter(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String delimiter)
	{
		getMendixObject().setValue(context, MemberNames.Delimiter.toString(), delimiter);
	}

	/**
	 * @return value of QuoteCharacter
	 */
	public final java.lang.String getQuoteCharacter()
	{
		return getQuoteCharacter(getContext());
	}

	/**
	 * @param context
	 * @return value of QuoteCharacter
	 */
	public final java.lang.String getQuoteCharacter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.QuoteCharacter.toString());
	}

	/**
	 * Set value of QuoteCharacter
	 * @param quotecharacter
	 */
	public final void setQuoteCharacter(java.lang.String quotecharacter)
	{
		setQuoteCharacter(getContext(), quotecharacter);
	}

	/**
	 * Set value of QuoteCharacter
	 * @param context
	 * @param quotecharacter
	 */
	public final void setQuoteCharacter(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String quotecharacter)
	{
		getMendixObject().setValue(context, MemberNames.QuoteCharacter.toString(), quotecharacter);
	}

	/**
	 * @return value of RecordSeparator
	 */
	public final java.lang.String getRecordSeparator()
	{
		return getRecordSeparator(getContext());
	}

	/**
	 * @param context
	 * @return value of RecordSeparator
	 */
	public final java.lang.String getRecordSeparator(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RecordSeparator.toString());
	}

	/**
	 * Set value of RecordSeparator
	 * @param recordseparator
	 */
	public final void setRecordSeparator(java.lang.String recordseparator)
	{
		setRecordSeparator(getContext(), recordseparator);
	}

	/**
	 * Set value of RecordSeparator
	 * @param context
	 * @param recordseparator
	 */
	public final void setRecordSeparator(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String recordseparator)
	{
		getMendixObject().setValue(context, MemberNames.RecordSeparator.toString(), recordseparator);
	}

	/**
	 * @return value of EscapeCharacter
	 */
	public final java.lang.String getEscapeCharacter()
	{
		return getEscapeCharacter(getContext());
	}

	/**
	 * @param context
	 * @return value of EscapeCharacter
	 */
	public final java.lang.String getEscapeCharacter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EscapeCharacter.toString());
	}

	/**
	 * Set value of EscapeCharacter
	 * @param escapecharacter
	 */
	public final void setEscapeCharacter(java.lang.String escapecharacter)
	{
		setEscapeCharacter(getContext(), escapecharacter);
	}

	/**
	 * Set value of EscapeCharacter
	 * @param context
	 * @param escapecharacter
	 */
	public final void setEscapeCharacter(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String escapecharacter)
	{
		getMendixObject().setValue(context, MemberNames.EscapeCharacter.toString(), escapecharacter);
	}

	/**
	 * @return value of Trim
	 */
	public final java.lang.Boolean getTrim()
	{
		return getTrim(getContext());
	}

	/**
	 * @param context
	 * @return value of Trim
	 */
	public final java.lang.Boolean getTrim(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Trim.toString());
	}

	/**
	 * Set value of Trim
	 * @param trim
	 */
	public final void setTrim(java.lang.Boolean trim)
	{
		setTrim(getContext(), trim);
	}

	/**
	 * Set value of Trim
	 * @param context
	 * @param trim
	 */
	public final void setTrim(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean trim)
	{
		getMendixObject().setValue(context, MemberNames.Trim.toString(), trim);
	}

	/**
	 * @return value of QuoteMode
	 */
	public final java.lang.String getQuoteMode()
	{
		return getQuoteMode(getContext());
	}

	/**
	 * @param context
	 * @return value of QuoteMode
	 */
	public final java.lang.String getQuoteMode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.QuoteMode.toString());
	}

	/**
	 * Set value of QuoteMode
	 * @param quotemode
	 */
	public final void setQuoteMode(java.lang.String quotemode)
	{
		setQuoteMode(getContext(), quotemode);
	}

	/**
	 * Set value of QuoteMode
	 * @param context
	 * @param quotemode
	 */
	public final void setQuoteMode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String quotemode)
	{
		getMendixObject().setValue(context, MemberNames.QuoteMode.toString(), quotemode);
	}

	/**
	 * @return value of DateTimeFormat
	 */
	public final java.lang.String getDateTimeFormat()
	{
		return getDateTimeFormat(getContext());
	}

	/**
	 * @param context
	 * @return value of DateTimeFormat
	 */
	public final java.lang.String getDateTimeFormat(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DateTimeFormat.toString());
	}

	/**
	 * Set value of DateTimeFormat
	 * @param datetimeformat
	 */
	public final void setDateTimeFormat(java.lang.String datetimeformat)
	{
		setDateTimeFormat(getContext(), datetimeformat);
	}

	/**
	 * Set value of DateTimeFormat
	 * @param context
	 * @param datetimeformat
	 */
	public final void setDateTimeFormat(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String datetimeformat)
	{
		getMendixObject().setValue(context, MemberNames.DateTimeFormat.toString(), datetimeformat);
	}

	/**
	 * @return value of ZoneId
	 */
	public final java.lang.String getZoneId()
	{
		return getZoneId(getContext());
	}

	/**
	 * @param context
	 * @return value of ZoneId
	 */
	public final java.lang.String getZoneId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ZoneId.toString());
	}

	/**
	 * Set value of ZoneId
	 * @param zoneid
	 */
	public final void setZoneId(java.lang.String zoneid)
	{
		setZoneId(getContext(), zoneid);
	}

	/**
	 * Set value of ZoneId
	 * @param context
	 * @param zoneid
	 */
	public final void setZoneId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String zoneid)
	{
		getMendixObject().setValue(context, MemberNames.ZoneId.toString(), zoneid);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return csvFormatMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final twowaysql.proxies.CsvFormat that = (twowaysql.proxies.CsvFormat) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
