// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package twowaysql.proxies;

public class TwoSqlTestResult implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject twoSqlTestResultMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TwoWaySQL.TwoSqlTestResult";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FilePath("FilePath"),
		RelativePath("RelativePath"),
		SqlStatement("SqlStatement"),
		TestStatus("TestStatus"),
		StackTrace("StackTrace"),
		ReturnEntityType("ReturnEntityType"),
		ElapsedTime("ElapsedTime"),
		DataSourceName("DataSourceName");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TwoSqlTestResult(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TwoSqlTestResult(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject twoSqlTestResultMendixObject)
	{
		if (twoSqlTestResultMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!twoSqlTestResultMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.twoSqlTestResultMendixObject = twoSqlTestResultMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static twowaysql.proxies.TwoSqlTestResult initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new twowaysql.proxies.TwoSqlTestResult(context, mendixObject);
	}

	public static twowaysql.proxies.TwoSqlTestResult load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return twowaysql.proxies.TwoSqlTestResult.initialize(context, mendixObject);
	}

	/**
	 * @return value of FilePath
	 */
	public final java.lang.String getFilePath()
	{
		return getFilePath(getContext());
	}

	/**
	 * @param context
	 * @return value of FilePath
	 */
	public final java.lang.String getFilePath(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FilePath.toString());
	}

	/**
	 * Set value of FilePath
	 * @param filepath
	 */
	public final void setFilePath(java.lang.String filepath)
	{
		setFilePath(getContext(), filepath);
	}

	/**
	 * Set value of FilePath
	 * @param context
	 * @param filepath
	 */
	public final void setFilePath(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String filepath)
	{
		getMendixObject().setValue(context, MemberNames.FilePath.toString(), filepath);
	}

	/**
	 * @return value of RelativePath
	 */
	public final java.lang.String getRelativePath()
	{
		return getRelativePath(getContext());
	}

	/**
	 * @param context
	 * @return value of RelativePath
	 */
	public final java.lang.String getRelativePath(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RelativePath.toString());
	}

	/**
	 * Set value of RelativePath
	 * @param relativepath
	 */
	public final void setRelativePath(java.lang.String relativepath)
	{
		setRelativePath(getContext(), relativepath);
	}

	/**
	 * Set value of RelativePath
	 * @param context
	 * @param relativepath
	 */
	public final void setRelativePath(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String relativepath)
	{
		getMendixObject().setValue(context, MemberNames.RelativePath.toString(), relativepath);
	}

	/**
	 * @return value of SqlStatement
	 */
	public final java.lang.String getSqlStatement()
	{
		return getSqlStatement(getContext());
	}

	/**
	 * @param context
	 * @return value of SqlStatement
	 */
	public final java.lang.String getSqlStatement(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SqlStatement.toString());
	}

	/**
	 * Set value of SqlStatement
	 * @param sqlstatement
	 */
	public final void setSqlStatement(java.lang.String sqlstatement)
	{
		setSqlStatement(getContext(), sqlstatement);
	}

	/**
	 * Set value of SqlStatement
	 * @param context
	 * @param sqlstatement
	 */
	public final void setSqlStatement(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sqlstatement)
	{
		getMendixObject().setValue(context, MemberNames.SqlStatement.toString(), sqlstatement);
	}

	/**
	 * @return value of TestStatus
	 */
	public final java.lang.String getTestStatus()
	{
		return getTestStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of TestStatus
	 */
	public final java.lang.String getTestStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TestStatus.toString());
	}

	/**
	 * Set value of TestStatus
	 * @param teststatus
	 */
	public final void setTestStatus(java.lang.String teststatus)
	{
		setTestStatus(getContext(), teststatus);
	}

	/**
	 * Set value of TestStatus
	 * @param context
	 * @param teststatus
	 */
	public final void setTestStatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String teststatus)
	{
		getMendixObject().setValue(context, MemberNames.TestStatus.toString(), teststatus);
	}

	/**
	 * @return value of StackTrace
	 */
	public final java.lang.String getStackTrace()
	{
		return getStackTrace(getContext());
	}

	/**
	 * @param context
	 * @return value of StackTrace
	 */
	public final java.lang.String getStackTrace(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.StackTrace.toString());
	}

	/**
	 * Set value of StackTrace
	 * @param stacktrace
	 */
	public final void setStackTrace(java.lang.String stacktrace)
	{
		setStackTrace(getContext(), stacktrace);
	}

	/**
	 * Set value of StackTrace
	 * @param context
	 * @param stacktrace
	 */
	public final void setStackTrace(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String stacktrace)
	{
		getMendixObject().setValue(context, MemberNames.StackTrace.toString(), stacktrace);
	}

	/**
	 * @return value of ReturnEntityType
	 */
	public final java.lang.String getReturnEntityType()
	{
		return getReturnEntityType(getContext());
	}

	/**
	 * @param context
	 * @return value of ReturnEntityType
	 */
	public final java.lang.String getReturnEntityType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReturnEntityType.toString());
	}

	/**
	 * Set value of ReturnEntityType
	 * @param returnentitytype
	 */
	public final void setReturnEntityType(java.lang.String returnentitytype)
	{
		setReturnEntityType(getContext(), returnentitytype);
	}

	/**
	 * Set value of ReturnEntityType
	 * @param context
	 * @param returnentitytype
	 */
	public final void setReturnEntityType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String returnentitytype)
	{
		getMendixObject().setValue(context, MemberNames.ReturnEntityType.toString(), returnentitytype);
	}

	/**
	 * @return value of ElapsedTime
	 */
	public final java.lang.Long getElapsedTime()
	{
		return getElapsedTime(getContext());
	}

	/**
	 * @param context
	 * @return value of ElapsedTime
	 */
	public final java.lang.Long getElapsedTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.ElapsedTime.toString());
	}

	/**
	 * Set value of ElapsedTime
	 * @param elapsedtime
	 */
	public final void setElapsedTime(java.lang.Long elapsedtime)
	{
		setElapsedTime(getContext(), elapsedtime);
	}

	/**
	 * Set value of ElapsedTime
	 * @param context
	 * @param elapsedtime
	 */
	public final void setElapsedTime(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long elapsedtime)
	{
		getMendixObject().setValue(context, MemberNames.ElapsedTime.toString(), elapsedtime);
	}

	/**
	 * @return value of DataSourceName
	 */
	public final java.lang.String getDataSourceName()
	{
		return getDataSourceName(getContext());
	}

	/**
	 * @param context
	 * @return value of DataSourceName
	 */
	public final java.lang.String getDataSourceName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DataSourceName.toString());
	}

	/**
	 * Set value of DataSourceName
	 * @param datasourcename
	 */
	public final void setDataSourceName(java.lang.String datasourcename)
	{
		setDataSourceName(getContext(), datasourcename);
	}

	/**
	 * Set value of DataSourceName
	 * @param context
	 * @param datasourcename
	 */
	public final void setDataSourceName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String datasourcename)
	{
		getMendixObject().setValue(context, MemberNames.DataSourceName.toString(), datasourcename);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return twoSqlTestResultMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final twowaysql.proxies.TwoSqlTestResult that = (twowaysql.proxies.TwoSqlTestResult) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
