// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoprofiler.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the NanoProfiler module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_DeleteInActiveStatusRecordsBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("NanoProfiler.ACT_DeleteInActiveStatusRecords");
		return builder;
	}

	public static void aCT_DeleteInActiveStatusRecords(IContext context)
	{
		aCT_DeleteInActiveStatusRecordsBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_DownloadActionStatisticsAsCSVBuilder(
		nanoprofiler.proxies.AutoNanoProfilerStatus _autoNanoProfilerStatus
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("NanoProfiler.ACT_DownloadActionStatisticsAsCSV");
		builder = builder.withParam("AutoNanoProfilerStatus", _autoNanoProfilerStatus);
		return builder;
	}

	public static void aCT_DownloadActionStatisticsAsCSV(
		IContext context,
		nanoprofiler.proxies.AutoNanoProfilerStatus _autoNanoProfilerStatus
	)
	{
		aCT_DownloadActionStatisticsAsCSVBuilder(
				_autoNanoProfilerStatus
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_DownloadAllActionStatisticsAsCSVBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("NanoProfiler.ACT_DownloadAllActionStatisticsAsCSV");
		return builder;
	}

	public static void aCT_DownloadAllActionStatisticsAsCSV(IContext context)
	{
		aCT_DownloadAllActionStatisticsAsCSVBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_DownloadAllMicroflowStatisticsAsCSVBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("NanoProfiler.ACT_DownloadAllMicroflowStatisticsAsCSV");
		return builder;
	}

	public static void aCT_DownloadAllMicroflowStatisticsAsCSV(IContext context)
	{
		aCT_DownloadAllMicroflowStatisticsAsCSVBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_DownloadAllRunningMicroflowsAsTXTBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("NanoProfiler.ACT_DownloadAllRunningMicroflowsAsTXT");
		return builder;
	}

	public static void aCT_DownloadAllRunningMicroflowsAsTXT(IContext context)
	{
		aCT_DownloadAllRunningMicroflowsAsTXTBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_DownloadMicroflowStatisticsAsCSVBuilder(
		nanoprofiler.proxies.AutoNanoProfilerStatus _autoNanoProfilerStatus
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("NanoProfiler.ACT_DownloadMicroflowStatisticsAsCSV");
		builder = builder.withParam("AutoNanoProfilerStatus", _autoNanoProfilerStatus);
		return builder;
	}

	public static void aCT_DownloadMicroflowStatisticsAsCSV(
		IContext context,
		nanoprofiler.proxies.AutoNanoProfilerStatus _autoNanoProfilerStatus
	)
	{
		aCT_DownloadMicroflowStatisticsAsCSVBuilder(
				_autoNanoProfilerStatus
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_DownloadRunningMicroflowsAsTXTBuilder(
		nanoprofiler.proxies.AutoNanoProfilerStatus _autoNanoProfilerStatus
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("NanoProfiler.ACT_DownloadRunningMicroflowsAsTXT");
		builder = builder.withParam("AutoNanoProfilerStatus", _autoNanoProfilerStatus);
		return builder;
	}

	public static void aCT_DownloadRunningMicroflowsAsTXT(
		IContext context,
		nanoprofiler.proxies.AutoNanoProfilerStatus _autoNanoProfilerStatus
	)
	{
		aCT_DownloadRunningMicroflowsAsTXTBuilder(
				_autoNanoProfilerStatus
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_ReConfigRequestBuilder(
		nanoprofiler.proxies.AutoNanoProfilerStatus _autoNanoProfilerStatus
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("NanoProfiler.ACT_ReConfigRequest");
		builder = builder.withParam("AutoNanoProfilerStatus", _autoNanoProfilerStatus);
		return builder;
	}

	public static void aCT_ReConfigRequest(
		IContext context,
		nanoprofiler.proxies.AutoNanoProfilerStatus _autoNanoProfilerStatus
	)
	{
		aCT_ReConfigRequestBuilder(
				_autoNanoProfilerStatus
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_SampleBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("NanoProfiler.ACT_Sample");
		return builder;
	}

	public static void aCT_Sample(IContext context)
	{
		aCT_SampleBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_SetReConfigRequestToAllBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("NanoProfiler.ACT_SetReConfigRequestToAll");
		return builder;
	}

	public static void aCT_SetReConfigRequestToAll(IContext context)
	{
		aCT_SetReConfigRequestToAllBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_ValidateRegexsBuilder(
		nanoprofiler.proxies.RegexpMatchValidation _regexpMatchValidation,
		nanoprofiler.proxies.AutoNanoProfilerConfig _autoNanoProfilerConfig
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("NanoProfiler.ACT_ValidateRegexs");
		builder = builder.withParam("RegexpMatchValidation", _regexpMatchValidation);
		builder = builder.withParam("AutoNanoProfilerConfig", _autoNanoProfilerConfig);
		return builder;
	}

	public static void aCT_ValidateRegexs(
		IContext context,
		nanoprofiler.proxies.RegexpMatchValidation _regexpMatchValidation,
		nanoprofiler.proxies.AutoNanoProfilerConfig _autoNanoProfilerConfig
	)
	{
		aCT_ValidateRegexsBuilder(
				_regexpMatchValidation,
				_autoNanoProfilerConfig
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aSU_AutoModeNanoProfilerBuilder(
		java.lang.String _configName
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("NanoProfiler.ASU_AutoModeNanoProfiler");
		builder = builder.withParam("ConfigName", _configName);
		return builder;
	}

	public static boolean aSU_AutoModeNanoProfiler(
		IContext context,
		java.lang.String _configName
	)
	{
		Object result = aSU_AutoModeNanoProfilerBuilder(
				_configName
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder bCO_AutoNanoProfilerConfigBuilder(
		nanoprofiler.proxies.AutoNanoProfilerConfig _autoNanoProfilerConfig
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("NanoProfiler.BCO_AutoNanoProfilerConfig");
		builder = builder.withParam("AutoNanoProfilerConfig", _autoNanoProfilerConfig);
		return builder;
	}

	public static boolean bCO_AutoNanoProfilerConfig(
		IContext context,
		nanoprofiler.proxies.AutoNanoProfilerConfig _autoNanoProfilerConfig
	)
	{
		Object result = bCO_AutoNanoProfilerConfigBuilder(
				_autoNanoProfilerConfig
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder bSD_AutoModeNanoProfilerBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("NanoProfiler.BSD_AutoModeNanoProfiler");
		return builder;
	}

	public static void bSD_AutoModeNanoProfiler(IContext context)
	{
		bSD_AutoModeNanoProfilerBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_RegexpMatchValidationBuilder(
		nanoprofiler.proxies.AutoNanoProfilerConfig _autoNanoProfilerConfig
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("NanoProfiler.DS_RegexpMatchValidation");
		builder = builder.withParam("AutoNanoProfilerConfig", _autoNanoProfilerConfig);
		return builder;
	}

	public static nanoprofiler.proxies.RegexpMatchValidation dS_RegexpMatchValidation(
		IContext context,
		nanoprofiler.proxies.AutoNanoProfilerConfig _autoNanoProfilerConfig
	)
	{
		Object result = dS_RegexpMatchValidationBuilder(
				_autoNanoProfilerConfig
			)
			.execute(context);
		return result == null ? null : nanoprofiler.proxies.RegexpMatchValidation.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_SampleBuilder(
		system.proxies.User _user
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("NanoProfiler.SUB_Sample");
		builder = builder.withParam("User", _user);
		return builder;
	}

	public static void sUB_Sample(
		IContext context,
		system.proxies.User _user
	)
	{
		sUB_SampleBuilder(
				_user
			)
			.execute(context);
	}
}
