// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoprofiler.proxies;

public class AutoNanoProfilerConfig implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject autoNanoProfilerConfigMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "NanoProfiler.AutoNanoProfilerConfig";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ConfigName("ConfigName"),
		ConfigVersionNum("ConfigVersionNum"),
		Description("Description"),
		IsEnable("IsEnable"),
		TraceActions("TraceActions"),
		CountSqls("CountSqls"),
		ReportThresholdMillis("ReportThresholdMillis"),
		ReportingLogLevel("ReportingLogLevel"),
		IncludeMicroflowsRegexp("IncludeMicroflowsRegexp"),
		ApplyRecursively("ApplyRecursively"),
		ExcludeMicroflowsRegexp("ExcludeMicroflowsRegexp"),
		ShowSqlStatements("ShowSqlStatements"),
		ShowMemoryUsage("ShowMemoryUsage"),
		RecordStatistics("RecordStatistics"),
		StateRunningMicroflows("StateRunningMicroflows"),
		UseIProfiler("UseIProfiler");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AutoNanoProfilerConfig(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected AutoNanoProfilerConfig(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject autoNanoProfilerConfigMendixObject)
	{
		if (autoNanoProfilerConfigMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!autoNanoProfilerConfigMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.autoNanoProfilerConfigMendixObject = autoNanoProfilerConfigMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static nanoprofiler.proxies.AutoNanoProfilerConfig initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new nanoprofiler.proxies.AutoNanoProfilerConfig(context, mendixObject);
	}

	public static nanoprofiler.proxies.AutoNanoProfilerConfig load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return nanoprofiler.proxies.AutoNanoProfilerConfig.initialize(context, mendixObject);
	}

	public static java.util.List<nanoprofiler.proxies.AutoNanoProfilerConfig> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> nanoprofiler.proxies.AutoNanoProfilerConfig.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of ConfigName
	 */
	public final java.lang.String getConfigName()
	{
		return getConfigName(getContext());
	}

	/**
	 * @param context
	 * @return value of ConfigName
	 */
	public final java.lang.String getConfigName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ConfigName.toString());
	}

	/**
	 * Set value of ConfigName
	 * @param configname
	 */
	public final void setConfigName(java.lang.String configname)
	{
		setConfigName(getContext(), configname);
	}

	/**
	 * Set value of ConfigName
	 * @param context
	 * @param configname
	 */
	public final void setConfigName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String configname)
	{
		getMendixObject().setValue(context, MemberNames.ConfigName.toString(), configname);
	}

	/**
	 * @return value of ConfigVersionNum
	 */
	public final java.lang.Long getConfigVersionNum()
	{
		return getConfigVersionNum(getContext());
	}

	/**
	 * @param context
	 * @return value of ConfigVersionNum
	 */
	public final java.lang.Long getConfigVersionNum(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.ConfigVersionNum.toString());
	}

	/**
	 * Set value of ConfigVersionNum
	 * @param configversionnum
	 */
	public final void setConfigVersionNum(java.lang.Long configversionnum)
	{
		setConfigVersionNum(getContext(), configversionnum);
	}

	/**
	 * Set value of ConfigVersionNum
	 * @param context
	 * @param configversionnum
	 */
	public final void setConfigVersionNum(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long configversionnum)
	{
		getMendixObject().setValue(context, MemberNames.ConfigVersionNum.toString(), configversionnum);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of IsEnable
	 */
	public final java.lang.Boolean getIsEnable()
	{
		return getIsEnable(getContext());
	}

	/**
	 * @param context
	 * @return value of IsEnable
	 */
	public final java.lang.Boolean getIsEnable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsEnable.toString());
	}

	/**
	 * Set value of IsEnable
	 * @param isenable
	 */
	public final void setIsEnable(java.lang.Boolean isenable)
	{
		setIsEnable(getContext(), isenable);
	}

	/**
	 * Set value of IsEnable
	 * @param context
	 * @param isenable
	 */
	public final void setIsEnable(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isenable)
	{
		getMendixObject().setValue(context, MemberNames.IsEnable.toString(), isenable);
	}

	/**
	 * @return value of TraceActions
	 */
	public final java.lang.Boolean getTraceActions()
	{
		return getTraceActions(getContext());
	}

	/**
	 * @param context
	 * @return value of TraceActions
	 */
	public final java.lang.Boolean getTraceActions(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.TraceActions.toString());
	}

	/**
	 * Set value of TraceActions
	 * @param traceactions
	 */
	public final void setTraceActions(java.lang.Boolean traceactions)
	{
		setTraceActions(getContext(), traceactions);
	}

	/**
	 * Set value of TraceActions
	 * @param context
	 * @param traceactions
	 */
	public final void setTraceActions(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean traceactions)
	{
		getMendixObject().setValue(context, MemberNames.TraceActions.toString(), traceactions);
	}

	/**
	 * @return value of CountSqls
	 */
	public final java.lang.Boolean getCountSqls()
	{
		return getCountSqls(getContext());
	}

	/**
	 * @param context
	 * @return value of CountSqls
	 */
	public final java.lang.Boolean getCountSqls(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CountSqls.toString());
	}

	/**
	 * Set value of CountSqls
	 * @param countsqls
	 */
	public final void setCountSqls(java.lang.Boolean countsqls)
	{
		setCountSqls(getContext(), countsqls);
	}

	/**
	 * Set value of CountSqls
	 * @param context
	 * @param countsqls
	 */
	public final void setCountSqls(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean countsqls)
	{
		getMendixObject().setValue(context, MemberNames.CountSqls.toString(), countsqls);
	}

	/**
	 * @return value of ReportThresholdMillis
	 */
	public final java.lang.Long getReportThresholdMillis()
	{
		return getReportThresholdMillis(getContext());
	}

	/**
	 * @param context
	 * @return value of ReportThresholdMillis
	 */
	public final java.lang.Long getReportThresholdMillis(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.ReportThresholdMillis.toString());
	}

	/**
	 * Set value of ReportThresholdMillis
	 * @param reportthresholdmillis
	 */
	public final void setReportThresholdMillis(java.lang.Long reportthresholdmillis)
	{
		setReportThresholdMillis(getContext(), reportthresholdmillis);
	}

	/**
	 * Set value of ReportThresholdMillis
	 * @param context
	 * @param reportthresholdmillis
	 */
	public final void setReportThresholdMillis(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long reportthresholdmillis)
	{
		getMendixObject().setValue(context, MemberNames.ReportThresholdMillis.toString(), reportthresholdmillis);
	}

	/**
	 * Get value of ReportingLogLevel
	 * @param reportingloglevel
	 */
	public final nanoprofiler.proxies.LogLevels getReportingLogLevel()
	{
		return getReportingLogLevel(getContext());
	}

	/**
	 * @param context
	 * @return value of ReportingLogLevel
	 */
	public final nanoprofiler.proxies.LogLevels getReportingLogLevel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ReportingLogLevel.toString());
		if (obj == null) {
			return null;
		}
		return nanoprofiler.proxies.LogLevels.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ReportingLogLevel
	 * @param reportingloglevel
	 */
	public final void setReportingLogLevel(nanoprofiler.proxies.LogLevels reportingloglevel)
	{
		setReportingLogLevel(getContext(), reportingloglevel);
	}

	/**
	 * Set value of ReportingLogLevel
	 * @param context
	 * @param reportingloglevel
	 */
	public final void setReportingLogLevel(com.mendix.systemwideinterfaces.core.IContext context, nanoprofiler.proxies.LogLevels reportingloglevel)
	{
		if (reportingloglevel != null) {
			getMendixObject().setValue(context, MemberNames.ReportingLogLevel.toString(), reportingloglevel.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.ReportingLogLevel.toString(), null);
		}
	}

	/**
	 * @return value of IncludeMicroflowsRegexp
	 */
	public final java.lang.String getIncludeMicroflowsRegexp()
	{
		return getIncludeMicroflowsRegexp(getContext());
	}

	/**
	 * @param context
	 * @return value of IncludeMicroflowsRegexp
	 */
	public final java.lang.String getIncludeMicroflowsRegexp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.IncludeMicroflowsRegexp.toString());
	}

	/**
	 * Set value of IncludeMicroflowsRegexp
	 * @param includemicroflowsregexp
	 */
	public final void setIncludeMicroflowsRegexp(java.lang.String includemicroflowsregexp)
	{
		setIncludeMicroflowsRegexp(getContext(), includemicroflowsregexp);
	}

	/**
	 * Set value of IncludeMicroflowsRegexp
	 * @param context
	 * @param includemicroflowsregexp
	 */
	public final void setIncludeMicroflowsRegexp(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String includemicroflowsregexp)
	{
		getMendixObject().setValue(context, MemberNames.IncludeMicroflowsRegexp.toString(), includemicroflowsregexp);
	}

	/**
	 * @return value of ApplyRecursively
	 */
	public final java.lang.Boolean getApplyRecursively()
	{
		return getApplyRecursively(getContext());
	}

	/**
	 * @param context
	 * @return value of ApplyRecursively
	 */
	public final java.lang.Boolean getApplyRecursively(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ApplyRecursively.toString());
	}

	/**
	 * Set value of ApplyRecursively
	 * @param applyrecursively
	 */
	public final void setApplyRecursively(java.lang.Boolean applyrecursively)
	{
		setApplyRecursively(getContext(), applyrecursively);
	}

	/**
	 * Set value of ApplyRecursively
	 * @param context
	 * @param applyrecursively
	 */
	public final void setApplyRecursively(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean applyrecursively)
	{
		getMendixObject().setValue(context, MemberNames.ApplyRecursively.toString(), applyrecursively);
	}

	/**
	 * @return value of ExcludeMicroflowsRegexp
	 */
	public final java.lang.String getExcludeMicroflowsRegexp()
	{
		return getExcludeMicroflowsRegexp(getContext());
	}

	/**
	 * @param context
	 * @return value of ExcludeMicroflowsRegexp
	 */
	public final java.lang.String getExcludeMicroflowsRegexp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ExcludeMicroflowsRegexp.toString());
	}

	/**
	 * Set value of ExcludeMicroflowsRegexp
	 * @param excludemicroflowsregexp
	 */
	public final void setExcludeMicroflowsRegexp(java.lang.String excludemicroflowsregexp)
	{
		setExcludeMicroflowsRegexp(getContext(), excludemicroflowsregexp);
	}

	/**
	 * Set value of ExcludeMicroflowsRegexp
	 * @param context
	 * @param excludemicroflowsregexp
	 */
	public final void setExcludeMicroflowsRegexp(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String excludemicroflowsregexp)
	{
		getMendixObject().setValue(context, MemberNames.ExcludeMicroflowsRegexp.toString(), excludemicroflowsregexp);
	}

	/**
	 * @return value of ShowSqlStatements
	 */
	public final java.lang.Boolean getShowSqlStatements()
	{
		return getShowSqlStatements(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowSqlStatements
	 */
	public final java.lang.Boolean getShowSqlStatements(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowSqlStatements.toString());
	}

	/**
	 * Set value of ShowSqlStatements
	 * @param showsqlstatements
	 */
	public final void setShowSqlStatements(java.lang.Boolean showsqlstatements)
	{
		setShowSqlStatements(getContext(), showsqlstatements);
	}

	/**
	 * Set value of ShowSqlStatements
	 * @param context
	 * @param showsqlstatements
	 */
	public final void setShowSqlStatements(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showsqlstatements)
	{
		getMendixObject().setValue(context, MemberNames.ShowSqlStatements.toString(), showsqlstatements);
	}

	/**
	 * @return value of ShowMemoryUsage
	 */
	public final java.lang.Boolean getShowMemoryUsage()
	{
		return getShowMemoryUsage(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowMemoryUsage
	 */
	public final java.lang.Boolean getShowMemoryUsage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowMemoryUsage.toString());
	}

	/**
	 * Set value of ShowMemoryUsage
	 * @param showmemoryusage
	 */
	public final void setShowMemoryUsage(java.lang.Boolean showmemoryusage)
	{
		setShowMemoryUsage(getContext(), showmemoryusage);
	}

	/**
	 * Set value of ShowMemoryUsage
	 * @param context
	 * @param showmemoryusage
	 */
	public final void setShowMemoryUsage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showmemoryusage)
	{
		getMendixObject().setValue(context, MemberNames.ShowMemoryUsage.toString(), showmemoryusage);
	}

	/**
	 * @return value of RecordStatistics
	 */
	public final java.lang.Boolean getRecordStatistics()
	{
		return getRecordStatistics(getContext());
	}

	/**
	 * @param context
	 * @return value of RecordStatistics
	 */
	public final java.lang.Boolean getRecordStatistics(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.RecordStatistics.toString());
	}

	/**
	 * Set value of RecordStatistics
	 * @param recordstatistics
	 */
	public final void setRecordStatistics(java.lang.Boolean recordstatistics)
	{
		setRecordStatistics(getContext(), recordstatistics);
	}

	/**
	 * Set value of RecordStatistics
	 * @param context
	 * @param recordstatistics
	 */
	public final void setRecordStatistics(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean recordstatistics)
	{
		getMendixObject().setValue(context, MemberNames.RecordStatistics.toString(), recordstatistics);
	}

	/**
	 * @return value of StateRunningMicroflows
	 */
	public final java.lang.Boolean getStateRunningMicroflows()
	{
		return getStateRunningMicroflows(getContext());
	}

	/**
	 * @param context
	 * @return value of StateRunningMicroflows
	 */
	public final java.lang.Boolean getStateRunningMicroflows(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.StateRunningMicroflows.toString());
	}

	/**
	 * Set value of StateRunningMicroflows
	 * @param staterunningmicroflows
	 */
	public final void setStateRunningMicroflows(java.lang.Boolean staterunningmicroflows)
	{
		setStateRunningMicroflows(getContext(), staterunningmicroflows);
	}

	/**
	 * Set value of StateRunningMicroflows
	 * @param context
	 * @param staterunningmicroflows
	 */
	public final void setStateRunningMicroflows(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean staterunningmicroflows)
	{
		getMendixObject().setValue(context, MemberNames.StateRunningMicroflows.toString(), staterunningmicroflows);
	}

	/**
	 * @return value of UseIProfiler
	 */
	public final java.lang.Boolean getUseIProfiler()
	{
		return getUseIProfiler(getContext());
	}

	/**
	 * @param context
	 * @return value of UseIProfiler
	 */
	public final java.lang.Boolean getUseIProfiler(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.UseIProfiler.toString());
	}

	/**
	 * Set value of UseIProfiler
	 * @param useiprofiler
	 */
	public final void setUseIProfiler(java.lang.Boolean useiprofiler)
	{
		setUseIProfiler(getContext(), useiprofiler);
	}

	/**
	 * Set value of UseIProfiler
	 * @param context
	 * @param useiprofiler
	 */
	public final void setUseIProfiler(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean useiprofiler)
	{
		getMendixObject().setValue(context, MemberNames.UseIProfiler.toString(), useiprofiler);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return autoNanoProfilerConfigMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final nanoprofiler.proxies.AutoNanoProfilerConfig that = (nanoprofiler.proxies.AutoNanoProfilerConfig) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
