// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoprofiler.proxies;

public enum LogLevels
{
	TRACE("f2d6f5ba-0a2b-41e5-8980-ba00c4e15f8f"),
	DEBUG("f72967c2-999c-4d7e-9351-2aa9afd04c83"),
	INFO("426e332d-e49f-4b4f-90d3-715ba538176f"),
	WARNING("b1c771c5-fdb1-456f-9a74-2e2f52f5383d"),
	ERROR("e09cf633-8591-41ab-b9da-5d7e960467c1"),
	CRITICAL("4afa0211-191c-4f43-b3f5-1b9fb7ed4d55"),
	NONE("8be0d6ff-0b42-4f25-a4c8-c366b0f7b803");

	private final java.lang.String i18nCaptionKey;
	
	private LogLevels(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
