// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoprofiler.proxies;

public enum LogLevels
{
	TRACE("d68512d6-f725-4793-8dce-286f903793e7"),
	DEBUG("259a4c92-6593-4627-9a00-3759d5dd0069"),
	INFO("6f5e1d54-d3e9-477a-8e30-f1414a37a537"),
	WARNING("35f6a6f0-0785-4f13-9244-e87213507e72"),
	ERROR("9569a474-a34b-4b80-8a44-af6d643ca824"),
	CRITICAL("289bde5c-fe27-4247-bf88-619b146bec55"),
	NONE("90e43a4f-6b2f-4cfb-a138-51204e4d3f64");

	private final java.lang.String i18nCaptionKey;
	
	private LogLevels(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
