// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoprofiler.proxies;

public class RegexpMatchValidation implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject regexpMatchValidationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "NanoProfiler.RegexpMatchValidation";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MicroflowNameForTest("MicroflowNameForTest"),
		MatchIncludeMicroflowsRegexp("MatchIncludeMicroflowsRegexp"),
		MatchExcludeMicroflowsRegexp("MatchExcludeMicroflowsRegexp"),
		MatchForProfilingTarget("MatchForProfilingTarget");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RegexpMatchValidation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected RegexpMatchValidation(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject regexpMatchValidationMendixObject)
	{
		if (regexpMatchValidationMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!regexpMatchValidationMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.regexpMatchValidationMendixObject = regexpMatchValidationMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static nanoprofiler.proxies.RegexpMatchValidation initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new nanoprofiler.proxies.RegexpMatchValidation(context, mendixObject);
	}

	public static nanoprofiler.proxies.RegexpMatchValidation load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return nanoprofiler.proxies.RegexpMatchValidation.initialize(context, mendixObject);
	}

	/**
	 * @return value of MicroflowNameForTest
	 */
	public final java.lang.String getMicroflowNameForTest()
	{
		return getMicroflowNameForTest(getContext());
	}

	/**
	 * @param context
	 * @return value of MicroflowNameForTest
	 */
	public final java.lang.String getMicroflowNameForTest(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MicroflowNameForTest.toString());
	}

	/**
	 * Set value of MicroflowNameForTest
	 * @param microflownamefortest
	 */
	public final void setMicroflowNameForTest(java.lang.String microflownamefortest)
	{
		setMicroflowNameForTest(getContext(), microflownamefortest);
	}

	/**
	 * Set value of MicroflowNameForTest
	 * @param context
	 * @param microflownamefortest
	 */
	public final void setMicroflowNameForTest(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String microflownamefortest)
	{
		getMendixObject().setValue(context, MemberNames.MicroflowNameForTest.toString(), microflownamefortest);
	}

	/**
	 * @return value of MatchIncludeMicroflowsRegexp
	 */
	public final java.lang.Boolean getMatchIncludeMicroflowsRegexp()
	{
		return getMatchIncludeMicroflowsRegexp(getContext());
	}

	/**
	 * @param context
	 * @return value of MatchIncludeMicroflowsRegexp
	 */
	public final java.lang.Boolean getMatchIncludeMicroflowsRegexp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.MatchIncludeMicroflowsRegexp.toString());
	}

	/**
	 * Set value of MatchIncludeMicroflowsRegexp
	 * @param matchincludemicroflowsregexp
	 */
	public final void setMatchIncludeMicroflowsRegexp(java.lang.Boolean matchincludemicroflowsregexp)
	{
		setMatchIncludeMicroflowsRegexp(getContext(), matchincludemicroflowsregexp);
	}

	/**
	 * Set value of MatchIncludeMicroflowsRegexp
	 * @param context
	 * @param matchincludemicroflowsregexp
	 */
	public final void setMatchIncludeMicroflowsRegexp(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean matchincludemicroflowsregexp)
	{
		getMendixObject().setValue(context, MemberNames.MatchIncludeMicroflowsRegexp.toString(), matchincludemicroflowsregexp);
	}

	/**
	 * @return value of MatchExcludeMicroflowsRegexp
	 */
	public final java.lang.Boolean getMatchExcludeMicroflowsRegexp()
	{
		return getMatchExcludeMicroflowsRegexp(getContext());
	}

	/**
	 * @param context
	 * @return value of MatchExcludeMicroflowsRegexp
	 */
	public final java.lang.Boolean getMatchExcludeMicroflowsRegexp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.MatchExcludeMicroflowsRegexp.toString());
	}

	/**
	 * Set value of MatchExcludeMicroflowsRegexp
	 * @param matchexcludemicroflowsregexp
	 */
	public final void setMatchExcludeMicroflowsRegexp(java.lang.Boolean matchexcludemicroflowsregexp)
	{
		setMatchExcludeMicroflowsRegexp(getContext(), matchexcludemicroflowsregexp);
	}

	/**
	 * Set value of MatchExcludeMicroflowsRegexp
	 * @param context
	 * @param matchexcludemicroflowsregexp
	 */
	public final void setMatchExcludeMicroflowsRegexp(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean matchexcludemicroflowsregexp)
	{
		getMendixObject().setValue(context, MemberNames.MatchExcludeMicroflowsRegexp.toString(), matchexcludemicroflowsregexp);
	}

	/**
	 * @return value of MatchForProfilingTarget
	 */
	public final java.lang.Boolean getMatchForProfilingTarget()
	{
		return getMatchForProfilingTarget(getContext());
	}

	/**
	 * @param context
	 * @return value of MatchForProfilingTarget
	 */
	public final java.lang.Boolean getMatchForProfilingTarget(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.MatchForProfilingTarget.toString());
	}

	/**
	 * Set value of MatchForProfilingTarget
	 * @param matchforprofilingtarget
	 */
	public final void setMatchForProfilingTarget(java.lang.Boolean matchforprofilingtarget)
	{
		setMatchForProfilingTarget(getContext(), matchforprofilingtarget);
	}

	/**
	 * Set value of MatchForProfilingTarget
	 * @param context
	 * @param matchforprofilingtarget
	 */
	public final void setMatchForProfilingTarget(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean matchforprofilingtarget)
	{
		getMendixObject().setValue(context, MemberNames.MatchForProfilingTarget.toString(), matchforprofilingtarget);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return regexpMatchValidationMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final nanoprofiler.proxies.RegexpMatchValidation that = (nanoprofiler.proxies.RegexpMatchValidation) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
