// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twowaysql.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import twowaysql.implementation.TwoWaySqlExecutor;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Specify the parameters by List for the in-clause
 * You can only use entity types as below.
 * - TwoWaySql.LongValue
 * - TwoWaySql.DecimalValue
 * - TwoWaySql.DateTimeValue
 * - TwoWaySql.BooleanValue
 * - TwoWaySql.StringValue
 */
public class AddListParameter extends UserAction<java.lang.Boolean>
{
	private final java.lang.String name;
	private final java.util.List<IMendixObject> value;

	public AddListParameter(
		IContext context,
		java.lang.String _name,
		java.util.List<IMendixObject> _value
	)
	{
		super(context);
		this.name = _name;
		this.value = _value;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		java.util.List<IMendixObject> listParam = this.value;
		if (listParam != null && listParam.size() == 0) {
			listParam = null;
		}
		TwoWaySqlExecutor.addParameter(this.name, listParam);
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "AddListParameter";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
