// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twowaysql.actions;

import java.util.Map;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.IMendixObjectMember;
import twowaysql.implementation.TwoWaySqlExecutor;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Specify the parameters at once from the entity.
 * The attribute name is mapped to the parameter name.
 * 
 * 
 */
public class AddParametersFromEntity extends UserAction<java.lang.Void>
{
	private final IMendixObject ParameterEntity;

	public AddParametersFromEntity(
		IContext context,
		IMendixObject _parameterEntity
	)
	{
		super(context);
		this.ParameterEntity = _parameterEntity;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
	    Map<String, ? extends IMendixObjectMember<?>> momMap = ParameterEntity.getMembers(getContext());
	    for (String key : momMap.keySet()) {
	        Object o = momMap.get(key).getValue(getContext());
	        TwoWaySqlExecutor.addParameter(key, o);
	    }
	    return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "AddParametersFromEntity";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
