// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twowaysql.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import twowaysql.implementation.ParameterUtilForCursorLoop;
import com.mendix.systemwideinterfaces.core.UserAction;

public class AddParameterListForCursorLoop extends UserAction<java.lang.Void>
{
	private final java.lang.String name;
	private final java.util.List<IMendixObject> parameterList;

	public AddParameterListForCursorLoop(
		IContext context,
		java.lang.String _name,
		java.util.List<IMendixObject> _parameterList
	)
	{
		super(context);
		this.name = _name;
		this.parameterList = _parameterList;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		ParameterUtilForCursorLoop.addParameter(this.name, this.parameterList);
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "AddParameterListForCursorLoop";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
