// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twowaysql.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import twowaysql.implementation.BatchFetchHandler;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Registers TwoWaySQL to retrieve non-persistent entities (NPEs) used in the batch fetch loop.
 */
public class AddTwoWaySQLToRetrieveNPEs extends UserAction<java.lang.Void>
{
	private final java.lang.String fetchHandle;
	private final java.lang.String twoWaySQLFileName;
	private final java.lang.String npeType;

	public AddTwoWaySQLToRetrieveNPEs(
		IContext context,
		java.lang.String _fetchHandle,
		java.lang.String _twoWaySQLFileName,
		java.lang.String _npeType
	)
	{
		super(context);
		this.fetchHandle = _fetchHandle;
		this.twoWaySQLFileName = _twoWaySQLFileName;
		this.npeType = _npeType;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		BatchFetchHandler handler = BatchFetchHandler.getBatchFetchHandler(fetchHandle, getContext());
		if (handler == null) {
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException("No batch fetch handler found for handle: " + fetchHandle);
		}
		handler.addTwoWaySQLToRetrieveNPEs(twoWaySQLFileName, npeType);
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "AddTwoWaySQLToRetrieveNPEs";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
