// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twowaysql.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import twowaysql.implementation.BatchFetchHandler;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * This action performs batch commit with a size of constant BATCH_COMMIT_SIZE. The batch commit count is managed per entity. Also, be sure to call the CloseBatchFetchLoop action to commit the last chunk.
 */
public class BatchCommit extends UserAction<java.lang.Void>
{
	private final java.lang.String fetchHandle;
	private final IMendixObject objectToCommit;
	private final java.lang.Long batchCommitSize;

	public BatchCommit(
		IContext context,
		java.lang.String _fetchHandle,
		IMendixObject _objectToCommit,
		java.lang.Long _batchCommitSize
	)
	{
		super(context);
		this.fetchHandle = _fetchHandle;
		this.objectToCommit = _objectToCommit;
		this.batchCommitSize = _batchCommitSize;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		BatchFetchHandler handler = BatchFetchHandler.getBatchFetchHandler(fetchHandle, getContext());
		handler.batchCommit(getContext(), objectToCommit, batchCommitSize);
		return null; // Return type is Void, so we return null
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "BatchCommit";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
