// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twowaysql.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import twowaysql.implementation.BatchFetchHandler;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Starts a batch fetch loop by TwoWaySQL.
 * Executes TwoWaySQL to retrieve only the ID value of the target entities as a long value, loading only the ID value into memory (It only takes 8bytes of memory for every 1 items.),  and preparing to use the GetNext/GetJoinee action in the subsequent loop to retrieve the data of each record as a persistent entity object.
 * Persistent entities are fetched internally in batches up to BatchFetchCount by Core.retrieveIdList(), making it possible to optimize the balance between the number of SQL statements executed and memory usage without adding complex logic to the app.
 * The TwoWaySQL's select clause have to return the value of the id column of the target entity at the first column. Then followed by joined entities ID if you need.
 * Like as below,
 * select
 *   u.id as IdValue
 *   ,l.id as  IdValueOfLang
 * from
 *   system$user as u
 *   inner join system$user_language ul on ul.system$userid = u.id
 *   inner join system$language l on l.id = ul.system$languageid
 * where
 *  ...
 * 
 * NOTE: When joining, make sure that the first ID in the select clause - the join base Entity - does not contain duplicates or nulls.
 * Note: If your app needs to store all retrieved objects in app's List, this feature is pointless. Please apply it for batch processing where you iterate over large amounts of data and only update/delete or aggregate/compute them.
 * 
 */
public class BatchFetchLoopByTwoWaySQL extends UserAction<java.lang.String>
{
	private final java.lang.String twoWaySQLFileName;
	private final IMendixObject parameter;
	private final java.lang.Long batchFetchCount;
	private final java.lang.Long joineeCacheSize;

	public BatchFetchLoopByTwoWaySQL(
		IContext context,
		java.lang.String _twoWaySQLFileName,
		IMendixObject _parameter,
		java.lang.Long _batchFetchCount,
		java.lang.Long _joineeCacheSize
	)
	{
		super(context);
		this.twoWaySQLFileName = _twoWaySQLFileName;
		this.parameter = _parameter;
		this.batchFetchCount = _batchFetchCount;
		this.joineeCacheSize = _joineeCacheSize;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			String handle= BatchFetchHandler.createBatchFetchHandler(getContext(), twoWaySQLFileName, parameter, batchFetchCount, joineeCacheSize);
			return handle;
		} finally {
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "BatchFetchLoopByTwoWaySQL";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
