// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twowaysql.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import twowaysql.implementation.BatchFetchHandler;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * The work data of the batch fetch loop started by BatchFetchLoopByTwoWaySQL is automatically garbage collected, but for safety reasons it can be explicitly deleted by this Action.
 * Note: If you use the BatchCommit action, be sure to call the CloseBatchFetchLoop action to commit the last chunk.
 */
public class CloseBatchFetchLoop extends UserAction<java.lang.Boolean>
{
	private final java.lang.String fetchHandle;

	public CloseBatchFetchLoop(
		IContext context,
		java.lang.String _fetchHandle
	)
	{
		super(context);
		this.fetchHandle = _fetchHandle;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		boolean result = BatchFetchHandler.closeBatchFetchHandler(fetchHandle, getContext());
		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CloseBatchFetchLoop";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
