// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twowaysql.actions;

import java.util.ArrayList;
import java.util.List;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import twowaysql.implementation.TwoWaySqlExecutor;

/**
 * Execute the select 2WaySQL that sandwiched with 'SELECT COUNT(*) FROM (' and ') as count_table' and retuen the result.
 * Please use non-persistent Entity for search condition.
 * 
 * About 2WaySQL , See also
 * http://dbflute.seasar.org/ja/manual/function/ormapper/outsidesql/about.html#twowaysql
 * Due to the specification of Dbflute, You have to use the parameter prefix 'pmb.'
 * 
 */
public class CountRowsByTwoWaySql extends UserAction<java.lang.Long>
{
	private final java.lang.String TwoWaySqlFileName;
	private final IMendixObject Parameter;

	public CountRowsByTwoWaySql(
		IContext context,
		java.lang.String _twoWaySqlFileName,
		IMendixObject _parameter
	)
	{
		super(context);
		this.TwoWaySqlFileName = _twoWaySqlFileName;
		this.Parameter = _parameter;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		String mockDirective = TwoWaySqlExecutor.getMockDirective(TwoWaySqlFileName);
		if (mockDirective != null) {
			// MOCK interruption: retrieve by 2WaySQL is mocked, so return the mock result 
			java.lang.Long count = TwoWaySqlExecutor.mockCountRowsByTwoWaySql(getContext(), mockDirective, Parameter);
			logger.warn("CountRowsByTwoWaySql '" + TwoWaySqlFileName + "' is mocked by directive: " + mockDirective + ", returning " + count + " records.\n");
			return count;
		}

        List<IMendixObject> resultList = new ArrayList<IMendixObject>();
		TwoWaySqlExecutor twoWaySqlExecutor = new TwoWaySqlExecutor();
		return (long)twoWaySqlExecutor.selectByTwoWaySql(getContext(), TwoWaySqlFileName, Parameter, null, resultList, null, 0, true);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CountRowsByTwoWaySql";
	}

	// BEGIN EXTRA CODE
	public static final ILogNode logger = Core.getLogger("TwoWaySql");
	// END EXTRA CODE
}
