// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twowaysql.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import twowaysql.implementation.TwoWaySqlExecutor;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * It iterates over the execution results of TwoWaySQL using a cursor. Since it invokes a callback for each record rather than loading the entire result set, processing can be performed with low memory usage.
 * Please use non-persistent Entity for search condition and search result.
 * 
 * About 2WaySQL , See also
 * http://dbflute.seasar.org/ja/manual/function/ormapper/outsidesql/about.html#twowaysql
 * Due to the specification of Dbflute, You have to use the parameter prefix 'pmb.'
 * 
 */
public class CursorLoopOnTwoWaySql extends UserAction<java.lang.Long>
{
	private final java.lang.String TwoWaySqlFileName;
	private final IMendixObject SqlParameter;
	private final java.lang.String ResultEntityType;
	private final java.lang.String CallBackMicroflow;

	public CursorLoopOnTwoWaySql(
		IContext context,
		java.lang.String _twoWaySqlFileName,
		IMendixObject _sqlParameter,
		java.lang.String _resultEntityType,
		java.lang.String _callBackMicroflow
	)
	{
		super(context);
		this.TwoWaySqlFileName = _twoWaySqlFileName;
		this.SqlParameter = _sqlParameter;
		this.ResultEntityType = _resultEntityType;
		this.CallBackMicroflow = _callBackMicroflow;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		TwoWaySqlExecutor twoWaySqlExecutor = new TwoWaySqlExecutor();
		int count = twoWaySqlExecutor.selectByTwoWaySql(getContext(), TwoWaySqlFileName, SqlParameter, ResultEntityType, null, CallBackMicroflow, 0);
        return (long)count;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CursorLoopOnTwoWaySql";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
