// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twowaysql.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import twowaysql.implementation.TwoWaySqlExecutor;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * You can delete Persistent-Entity by 2WaySQL which returns ID column as 'IdValue'.
 * Based on the ID selected by 2WaySQL, PEs are retrieved in bulk using Core.retrieveIdList(IContext, List<IMendixIdentifier>)  then will be deleted by Core.delete(IContext, List<IMendixObject>).
 * Note: For Mendix v11.6 or later, it is more efficient to perform deletions using OQL.
 * 
 * About 2WaySQL , See also
 * http://dbflute.seasar.org/ja/manual/function/ormapper/outsidesql/about.html#twowaysql
 * Due to the specification of Dbflute, You have to use the parameter prefix 'pmb.'
 */
public class DeletePeByTwoWaySql extends UserAction<java.lang.Long>
{
	private final java.lang.String TwoWaySqlFileName;
	private final IMendixObject Parameter;
	private final java.lang.Long BatchDeleteSize;

	public DeletePeByTwoWaySql(
		IContext context,
		java.lang.String _twoWaySqlFileName,
		IMendixObject _parameter,
		java.lang.Long _batchDeleteSize
	)
	{
		super(context);
		this.TwoWaySqlFileName = _twoWaySqlFileName;
		this.Parameter = _parameter;
		this.BatchDeleteSize = _batchDeleteSize;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		TwoWaySqlExecutor twoWaySqlExecutor = new TwoWaySqlExecutor();
		long deletedCount = twoWaySqlExecutor.deleteByTwoWaySql(getContext(), TwoWaySqlFileName, Parameter, BatchDeleteSize.intValue());
		return deletedCount;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "DeletePeByTwoWaySql";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
