// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twowaysql.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

public class EndTranOnExternalDataSource extends UserAction<java.lang.Void>
{
	private final java.lang.String ExternalDataSourceName;

	public EndTranOnExternalDataSource(
		IContext context,
		java.lang.String _externalDataSourceName
	)
	{
		super(context);
		this.ExternalDataSourceName = _externalDataSourceName;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		twowaysql.integration.ExtDataSourceTransactionManager.endTransaction(getContext(), ExternalDataSourceName);
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "EndTranOnExternalDataSource";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
