// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twowaysql.actions;

import java.io.BufferedInputStream;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.time.ZoneId;
import java.util.TimeZone;
import org.apache.commons.csv.CSVFormat;
import org.apache.commons.csv.CSVPrinter;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import twowaysql.implementation.CSVFormatUtil;
import twowaysql.implementation.TwoWaySqlExecutor;
import twowaysql.proxies.constants.Constants;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Execute TwoWaySQL and output directly from the JDBC ResultSet to a CSV file.
 * It is fast and memory-saving because it is output to the CSV file in the cursor loop without going through the Entity of Mendix.
 * However, it is necessary to format the data into String for output to CSV in SQL. In particular, the date and time type needs to be formatted into String in SQL, including consideration of the time zone, so be careful.
 * 
 * Please use non-persistent Entity for search condition.
 * 
 * About 2WaySQL , See also
 * http://dbflute.seasar.org/ja/manual/function/ormapper/outsidesql/about.html#twowaysql
 * 
 * You have to use the parameter prefix 'pmb.'
 * 
 */
public class ExportCsvByTwoWaySql extends UserAction<java.lang.Long>
{
	private final java.lang.String TwoWaySqlFileName;
	private final IMendixObject Parameter;
	/** @deprecated use CsvFormat.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __CsvFormat;
	private final twowaysql.proxies.CsvFormat CsvFormat;
	private final java.lang.String CharacterSet;
	/** @deprecated use CsvFileDocument.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __CsvFileDocument;
	private final system.proxies.FileDocument CsvFileDocument;

	public ExportCsvByTwoWaySql(
		IContext context,
		java.lang.String _twoWaySqlFileName,
		IMendixObject _parameter,
		IMendixObject _csvFormat,
		java.lang.String _characterSet,
		IMendixObject _csvFileDocument
	)
	{
		super(context);
		this.TwoWaySqlFileName = _twoWaySqlFileName;
		this.Parameter = _parameter;
		this.__CsvFormat = _csvFormat;
		this.CsvFormat = _csvFormat == null ? null : twowaysql.proxies.CsvFormat.initialize(getContext(), _csvFormat);
		this.CharacterSet = _characterSet;
		this.__CsvFileDocument = _csvFileDocument;
		this.CsvFileDocument = _csvFileDocument == null ? null : system.proxies.FileDocument.initialize(getContext(), _csvFileDocument);
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		long recordCount = 0;

		final CSVFormat cmnCsvFormat = CSVFormatUtil.setupCSVFormat(CsvFormat);

		File tmpFile = File.createTempFile("export-", ".csv");
		try {
			try (final Writer writer = new BufferedWriter(new OutputStreamWriter(//
					new FileOutputStream(tmpFile), this.CharacterSet != null ? this.CharacterSet : "UTF-8"));
					final CSVPrinter csvPrinter = new CSVPrinter(writer, cmnCsvFormat)) {
				TwoWaySqlExecutor twoWaySqlExecutor = new TwoWaySqlExecutor();

				// mod by sugita.h (2022/09/30) start
				String dateTimeFormat = this.CsvFormat == null? null: this.CsvFormat.getDateTimeFormat();
				if (dateTimeFormat == null || dateTimeFormat.length() == 0) {
					dateTimeFormat = Constants.getDateTimeFormat();
				}

				//recordCount = twoWaySqlExecutor.exportCsvByTwoWaySql(getContext(), TwoWaySqlFileName, Parameter, csvPrinter, dateTimeFormat);
				// mod start by youta 2022/11/09
				String zoneId = this.CsvFormat == null? null: CsvFormat.getZoneId();
				if (zoneId == null) {
					TimeZone timeZone = getContext().getSession().getTimeZone();
					if (timeZone != null) {
						zoneId = timeZone.toZoneId().getId();
					} else {
						zoneId = SetDefaultTimeZoneIdForCsv.defaultTimeZoneIdForCsv;
					}
				}
				recordCount = twoWaySqlExecutor.exportCsvByTwoWaySql(getContext(), TwoWaySqlFileName, Parameter, csvPrinter, dateTimeFormat, ZoneId.of(zoneId));
				// mod end by youta 2022/11/09
				// mod by sugita.h (2022/09/30) end
			}

			String csvFileName = "";
			if (CsvFileDocument.getName() == null || CsvFileDocument.getName().isEmpty()) {
				csvFileName =tmpFile.getName();
			}else {
				csvFileName =CsvFileDocument.getName();
			}

			Core.storeFileDocumentContent(getContext(), CsvFileDocument.getMendixObject(), csvFileName,
					new BufferedInputStream(new FileInputStream(tmpFile)));
		} finally {
			tmpFile.delete();
		}

		return recordCount;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ExportCsvByTwoWaySql";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
