// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twowaysql.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import twowaysql.implementation.BatchFetchHandler;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Gets the join destination Object for the currently processed row.
 * The join destination object is batch fetched, so the select statement is not executed each time as in the standard Mendix association retrieve.
 * If you are processing a batch fetch loop with the following OQL, specify 'IdValueOfLang' in the aliasOfIdValue parameter to get the join destination System.Language.
 * select
 * CAST(user/ID as LONG) as IdValue
 * ,CAST(lang/ID as LONG) as IdValueOfLang
 * from
 * System.User user
 * inner join user/System.User_Language/System.Language lang
 * where
 * ...
 * 
 * The object retrieved with this action can be used in change/delete activities.
 */
public class GetJoinee extends UserAction<IMendixObject>
{
	private final java.lang.String fetchHandle;
	private final IMendixObject currentObject;
	private final java.lang.String aliasOfIdValue;
	private final java.lang.String joineeObjectType;

	public GetJoinee(
		IContext context,
		java.lang.String _fetchHandle,
		IMendixObject _currentObject,
		java.lang.String _aliasOfIdValue,
		java.lang.String _joineeObjectType
	)
	{
		super(context);
		this.fetchHandle = _fetchHandle;
		this.currentObject = _currentObject;
		this.aliasOfIdValue = _aliasOfIdValue;
		this.joineeObjectType = _joineeObjectType;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		BatchFetchHandler handler = BatchFetchHandler.getBatchFetchHandler(fetchHandle, getContext());
		if (handler == null) {
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException("No batch fetch handler found for handle: " + fetchHandle);
		}
		IMendixObject joinee = handler.getJoineePE(getContext(), currentObject, aliasOfIdValue);
		return joinee;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetJoinee";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
