// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twowaysql.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import twowaysql.implementation.InLineCursorLoopHandler;

/**
 * Get next object on inline cursor loop.
 * When the loop reaches the end and there is nothing left to fetch, it returns empty.
 * 
 */
public class GetNextByInLineCursor extends UserAction<IMendixObject>
{
	private final java.lang.String CursorHandle;
	private final java.lang.String ResultEntityType;

	public GetNextByInLineCursor(
		IContext context,
		java.lang.String _cursorHandle,
		java.lang.String _resultEntityType
	)
	{
		super(context);
		this.CursorHandle = _cursorHandle;
		this.ResultEntityType = _resultEntityType;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		InLineCursorLoopHandler handler = InLineCursorLoopHandler.getInLineCursorLoopHandler(getContext(), CursorHandle);
		return handler.getNext(getContext(), CursorHandle, ResultEntityType);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetNextByInLineCursor";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
