// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twowaysql.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Generates an SQL `ORDER BY` string based on the on-screen sort specifications found within the DataGrid2 `GridState` JSON string.
 * This string can be used as an embedded parameter for TwoWaySQL.
 * Note:
 * As of Mendix v11.12, Data Grid 2 does not provide a standard feature (event handler) to capture the "standard column header click" event and automatically trigger a backend microflow; therefore, the use cases for this action may be limited.
 */
public class GetOrderByFromGridState extends UserAction<java.lang.String>
{
	private final java.lang.String GridStateJson;
	private final java.lang.String ColumnMapping;
	private final java.lang.String DefaultSort;

	public GetOrderByFromGridState(
		IContext context,
		java.lang.String _gridStateJson,
		java.lang.String _columnMapping,
		java.lang.String _defaultSort
	)
	{
		super(context);
		this.GridStateJson = _gridStateJson;
		this.ColumnMapping = _columnMapping;
		this.DefaultSort = _defaultSort;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (GridStateJson == null || GridStateJson.isEmpty() || ColumnMapping == null || ColumnMapping.isEmpty()) {
			return DefaultSort != null ? DefaultSort : "";
		}

		String[] columns = ColumnMapping.split(",");
		java.util.List<String> orderByList = new java.util.ArrayList<>();

		// "sortOrder" の中にある ["数字", "asc|desc"] を直接まとめて抽出する正規表現
		java.util.regex.Pattern pattern = java.util.regex.Pattern.compile(
				"\"sortOrder\"\\s*:\\s*\\[.*?\\[\\s*\"(\\d+)\"\\s*,\\s*\"(asc|desc)\"\\s*\\]");
		java.util.regex.Matcher matcher = pattern.matcher(GridStateJson);

		// マッチした場合（グループ1: 数字、グループ2: asc/desc）
		if (matcher.find()) {
			int columnIndex = Integer.parseInt(matcher.group(1));
			String direction = matcher.group(2).toUpperCase();

			if (columnIndex >= 0 && columnIndex < columns.length) {
				String columnName = columns[columnIndex].trim();
				// SQLインジェクション対策：
				// 英数字、アンダースコア、ドット(.)、およびダブルクォーテーション(") を許可
				if (columnName.matches("^[a-zA-Z0-9_.\"]+$")) {
					orderByList.add(columnName + " " + direction);
				}
			}
		}

		if (!orderByList.isEmpty()) {
			return String.join(", ", orderByList);
		}

		return DefaultSort != null ? DefaultSort : "";
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetOrderByFromGridState";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
