// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twowaysql.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import twowaysql.implementation.BatchFetchHandler;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Get related NPEs stored in the batch fetch loop by TwoWaySQL spacified by AddTwoWaySQLToRetrieveNPEs action.
 * 
 */
public class GetRetrievedNPEs extends UserAction<java.util.List<IMendixObject>>
{
	private final java.lang.String fetchHandle;
	private final IMendixObject currentObject;
	private final java.lang.String npeType;

	public GetRetrievedNPEs(
		IContext context,
		java.lang.String _fetchHandle,
		IMendixObject _currentObject,
		java.lang.String _npeType
	)
	{
		super(context);
		this.fetchHandle = _fetchHandle;
		this.currentObject = _currentObject;
		this.npeType = _npeType;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		BatchFetchHandler handler = BatchFetchHandler.getBatchFetchHandler(fetchHandle, getContext());
		if (handler == null) {
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException("No batch fetch handler found for handle: " + fetchHandle);
		}
		return handler.getRetrievedNPEs(getContext(), currentObject, npeType);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetRetrievedNPEs";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
