// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twowaysql.actions;

import java.util.ArrayList;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import twowaysql.implementation.TwoWaySqlExecutor;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Store the result of the TwoWaySQL into the persistent entity.
 * 
 * About 2WaySQL , See also
 * http://dbflute.seasar.org/ja/manual/function/ormapper/outsidesql/about.html#twowaysql
 * However, due to the specification of MendixModeler, single quotes in 2 waySQL must be escaped with single quotes.
 * You have to use the parameter prefix 'pmb.'
 * 
 */
public class InsertSelectPeByTwoWaySql extends UserAction<java.lang.Long>
{
	private final java.lang.String TwoWaySqlFileName;
	private final IMendixObject Parameter;
	private final java.lang.String InsertEntityType;
	private final java.lang.Long BatchCommitSize;
	private final java.lang.String beforeBachCommitCallBackMicroflow;

	public InsertSelectPeByTwoWaySql(
		IContext context,
		java.lang.String _twoWaySqlFileName,
		IMendixObject _parameter,
		java.lang.String _insertEntityType,
		java.lang.Long _batchCommitSize,
		java.lang.String _beforeBachCommitCallBackMicroflow
	)
	{
		super(context);
		this.TwoWaySqlFileName = _twoWaySqlFileName;
		this.Parameter = _parameter;
		this.InsertEntityType = _insertEntityType;
		this.BatchCommitSize = _batchCommitSize;
		this.beforeBachCommitCallBackMicroflow = _beforeBachCommitCallBackMicroflow;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		TwoWaySqlExecutor twoWaySqlExecutor = new TwoWaySqlExecutor();
		int insertedCount = twoWaySqlExecutor.selectByTwoWaySql(getContext(), TwoWaySqlFileName, Parameter, InsertEntityType, new ArrayList<IMendixObject>(), beforeBachCommitCallBackMicroflow, BatchCommitSize.intValue());
        return (long)insertedCount;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "InsertSelectPeByTwoWaySql";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
