// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twowaysql.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import twowaysql.implementation.InLineCursorLoopHandler;

/**
 * It starts iteration over the execution ResultSet of TwoWaySQL using cursor operation. Since it fetches and returns each record by GetNextByInLineCursor action rather than loading the entire result set, processing can be performed with low memory usage.
 * 
 * Compared to using `CursorLoopOnTwoWaySql`, this approach allows you to write the loop directly in the Microflow logic rather than using a callback, resulting in a more understandable implementation. However, due to the nature of this implementation—which requires returning control to the Microflow while keeping the ResultSet open—it supports only external databases. This limitation exists because, with internal databases, the ResultSet/Statement/Connection are accessible only within the arrow expression of `com.mendix.datastorage.DataStorage.executeWithConnection()`, making it impossible to return control to the Microflow while the ResultSet remains active.
 * 
 * Within a `CursorLoop`, you can execute a different TwoWaySQL statement against the same external database, or even nest `CursorLoop`s.
 * 
 * Please use non-persistent Entity for search condition and search result.
 * 
 * About 2WaySQL , See also
 * http://dbflute.seasar.org/ja/manual/function/ormapper/outsidesql/about.html#twowaysql
 * Due to the specification of Dbflute, You have to use the parameter prefix 'pmb.'
 * 
 */
public class OpenInLineCursorByTwoWaySql extends UserAction<java.lang.String>
{
	private final java.lang.String TwoWaySqlFileName;
	private final IMendixObject SqlParameter;

	public OpenInLineCursorByTwoWaySql(
		IContext context,
		java.lang.String _twoWaySqlFileName,
		IMendixObject _sqlParameter
	)
	{
		super(context);
		this.TwoWaySqlFileName = _twoWaySqlFileName;
		this.SqlParameter = _sqlParameter;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		String handle = InLineCursorLoopHandler.createInLineCursorLoopHandler(getContext(), TwoWaySqlFileName, SqlParameter);
        return handle;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "OpenInLineCursorByTwoWaySql";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
