// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twowaysql.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import twowaysql.implementation.BatchFetchHandler;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Peek next object on batch fetch loop.
 * Unlike the GetNext action, it does not advance the internal pointer, so it can be used to peek at the next data when determining whether a set break has occurred during a loop.
 * When the loop reaches the end and there is nothing left to retrieve, it returns empty.
 * 
 */
public class PeekNext extends UserAction<IMendixObject>
{
	private final java.lang.String fetchHandle;
	private final java.lang.String batchFtechObjectType;

	public PeekNext(
		IContext context,
		java.lang.String _fetchHandle,
		java.lang.String _batchFtechObjectType
	)
	{
		super(context);
		this.fetchHandle = _fetchHandle;
		this.batchFtechObjectType = _batchFtechObjectType;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		BatchFetchHandler handler = BatchFetchHandler.getBatchFetchHandler(fetchHandle, getContext());
		return handler.peekNext(getContext());
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "PeekNext";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
