// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twowaysql.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import twowaysql.integration.ExtDataSourceBinder;

/**
 * This is a sample implementation of `RegisterExternalDataSource` using SSL/TLS client certificate authentication (mTLS / TCPS).
 * To use this, you must configure the dependency for the Oracle JDBC driver in your application's module settings.
 */
public class RegisterOracleMtlsExternalDataSource extends UserAction<java.lang.Void>
{
	private final java.lang.String ExternalDataSourceName;
	private final java.lang.String Url;
	private final java.lang.String User;
	private final java.lang.String Password;
	private final java.lang.String KeyStore;
	private final java.lang.String KeyStorePassword;
	private final java.lang.String KeyStoreType;
	private final java.lang.String TrustStore;
	private final java.lang.String TrustStorePassword;
	private final java.lang.String TrustStoreType;
	private final java.lang.Long Options;

	public RegisterOracleMtlsExternalDataSource(
		IContext context,
		java.lang.String _externalDataSourceName,
		java.lang.String _url,
		java.lang.String _user,
		java.lang.String _password,
		java.lang.String _keyStore,
		java.lang.String _keyStorePassword,
		java.lang.String _keyStoreType,
		java.lang.String _trustStore,
		java.lang.String _trustStorePassword,
		java.lang.String _trustStoreType,
		java.lang.Long _options
	)
	{
		super(context);
		this.ExternalDataSourceName = _externalDataSourceName;
		this.Url = _url;
		this.User = _user;
		this.Password = _password;
		this.KeyStore = _keyStore;
		this.KeyStorePassword = _keyStorePassword;
		this.KeyStoreType = _keyStoreType;
		this.TrustStore = _trustStore;
		this.TrustStorePassword = _trustStorePassword;
		this.TrustStoreType = _trustStoreType;
		this.Options = _options;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		ExtDataSourceBinder.putExtDataSource(ExternalDataSourceName, createOracleMtlsHikariDataSource());
		if (this.Options != null) {
			ExtDataSourceBinder.putExtDataSourceOptions(ExternalDataSourceName,  this.Options == null? 0 : this.Options);
		}
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "RegisterOracleMtlsExternalDataSource";
	}

	// BEGIN EXTRA CODE
	private HikariDataSource createOracleMtlsHikariDataSource() throws Exception {
		HikariConfig config = new HikariConfig();

		config.setJdbcUrl(Url);
		config.setUsername(User);
		config.setPassword(Password);
		config.setDriverClassName("oracle.jdbc.OracleDriver");

		config.setMinimumIdle(0);
		config.setPoolName(String.format("TwoWaySQL-Oracle-mTLS-HikaryCP-%d", getConnPoolKey()));

		config.addDataSourceProperty("javax.net.ssl.keyStore", Core.getConfiguration().getResourcesPath() + KeyStore);
        config.addDataSourceProperty("javax.net.ssl.keyStorePassword", KeyStorePassword);
        config.addDataSourceProperty("javax.net.ssl.keyStoreType", KeyStoreType);

        config.addDataSourceProperty("javax.net.ssl.trustStore", Core.getConfiguration().getResourcesPath() + TrustStore);
        config.addDataSourceProperty("javax.net.ssl.trustStorePassword", TrustStorePassword);
        config.addDataSourceProperty("javax.net.ssl.trustStoreType", TrustStoreType);

		return new HikariDataSource(config);
	}
	
	private Integer getConnPoolKey() {
		return (Url + User).hashCode();
	}

	// END EXTRA CODE
}
