// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twowaysql.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.zaxxer.hikari.HikariDataSource;
import twowaysql.integration.ExtDataSourceBinder;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * 外部DBを使用する場合は、本ActionをAfterStartUpから呼び出して、データソースを登録して下さい。
 * また、使用するJdbc Driverのjarファイルをuserlibフォルダに追加するか、Mendix v10.6以降であればモジュール設定のjava依存性設定でJdbc Driverのjarへの依存性を設定してvendorlibフォルダに自動ダウンロードされるようにして下さい。これはPostgreSQLであってもMendixランタイム側とは別クラスローダーとなるため必要です。
 */
public class RegisterExternalDataSource extends UserAction<java.lang.Void>
{
	private final java.lang.String ExternalDataSourceName;
	private final java.lang.String DriverClassName;
	private final java.lang.String Url;
	private final java.lang.String User;
	private final java.lang.String Password;
	private final java.lang.Long Options;

	public RegisterExternalDataSource(
		IContext context,
		java.lang.String _externalDataSourceName,
		java.lang.String _driverClassName,
		java.lang.String _url,
		java.lang.String _user,
		java.lang.String _password,
		java.lang.Long _options
	)
	{
		super(context);
		this.ExternalDataSourceName = _externalDataSourceName;
		this.DriverClassName = _driverClassName;
		this.Url = _url;
		this.User = _user;
		this.Password = _password;
		this.Options = _options;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		ExtDataSourceBinder.putExtDataSource(ExternalDataSourceName, createHikariDataSource());
		if (this.Options != null) {
			ExtDataSourceBinder.putExtDataSourceOptions(ExternalDataSourceName,  this.Options == null? 0 : this.Options);
		}
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "RegisterExternalDataSource";
	}

	// BEGIN EXTRA CODE
	private HikariDataSource createHikariDataSource() throws Exception {
		//Class.forName("org.postgresql.Driver");
		final HikariDataSource dataSource = new HikariDataSource();
		dataSource.setDriverClassName(DriverClassName);
		dataSource.setPoolName(String.format("TwoWaySQL-HikaryCP-%d", getConnPoolKey()));
		dataSource.setMinimumIdle(0);

		dataSource.setJdbcUrl(Url);
		dataSource.setUsername(User);
		dataSource.setPassword(Password);
		return dataSource;
	}
	
	private Integer getConnPoolKey() {
		return (Url + User).hashCode();
	}

	// END EXTRA CODE
}
