// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twowaysql.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Retrieve an entity by Mx Object ID.
 */
public class RetrieveById extends UserAction<IMendixObject>
{
	private final java.lang.Long IdValue;
	private final java.lang.String ResultEntityType;

	public RetrieveById(
		IContext context,
		java.lang.Long _idValue,
		java.lang.String _resultEntityType
	)
	{
		super(context);
		this.IdValue = _idValue;
		this.ResultEntityType = _resultEntityType;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
	    IMendixIdentifier mid = Core.createMendixIdentifier(IdValue);
	    IMendixObject reto = Core.retrieveId(getContext(), mid);
	    return reto;
		//throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "RetrieveById";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
