// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twowaysql.actions;

import java.util.ArrayList;
import java.util.List;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import twowaysql.implementation.TwoWaySqlExecutor;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Execute the select 2WaySQL and load the results into a list of the specified non-persistent entities.
 * Please use non-persistent Entity for search condition and search result.
 * 
 * About 2WaySQL , See also
 * http://dbflute.seasar.org/ja/manual/function/ormapper/outsidesql/about.html#twowaysql
 * Due to the specification of Dbflute, You have to use the parameter prefix 'pmb.'
 * 
 */
public class RetrieveByTwoWaySql extends UserAction<java.util.List<IMendixObject>>
{
	private final java.lang.String TwoWaySqlFileName;
	private final IMendixObject Parameter;
	private final java.lang.String ResultEntityType;

	public RetrieveByTwoWaySql(
		IContext context,
		java.lang.String _twoWaySqlFileName,
		IMendixObject _parameter,
		java.lang.String _resultEntityType
	)
	{
		super(context);
		this.TwoWaySqlFileName = _twoWaySqlFileName;
		this.Parameter = _parameter;
		this.ResultEntityType = _resultEntityType;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
        List<IMendixObject> resultList = new ArrayList<IMendixObject>();
		TwoWaySqlExecutor twoWaySqlExecutor = new TwoWaySqlExecutor();
		twoWaySqlExecutor.selectByTwoWaySql(getContext(), TwoWaySqlFileName, Parameter, ResultEntityType, resultList, null, 0);
        return resultList;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "RetrieveByTwoWaySql";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
