// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twowaysql.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Sets the default timezone when converting date-and-ftime type field data to CSV.
 * This can be overridden by the CsvFormat parameter when calling individual ExportCsvByTwoWaySql actions.
 * This action should be called by ASU(AfterStartUp).
 */
public class SetDefaultTimeZoneIdForCsv extends UserAction<java.lang.Void>
{
	private final java.lang.String zoneId;

	public SetDefaultTimeZoneIdForCsv(
		IContext context,
		java.lang.String _zoneId
	)
	{
		super(context);
		this.zoneId = _zoneId;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		defaultTimeZoneIdForCsv = zoneId;
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetDefaultTimeZoneIdForCsv";
	}

	// BEGIN EXTRA CODE
	static String defaultTimeZoneIdForCsv = "UTC";
	// END EXTRA CODE
}
