// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twowaysql.actions;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Stack;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.sql.DataSource;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.IMendixObjectMember;
import twowaysql.implementation.TwoWaySqlExecutor;
import twowaysql.integration.ExtDataSourceBinder;
import twowaysql.proxies.TwoSqlTestResult;
import com.mendix.systemwideinterfaces.core.UserAction;

public class TestTwoWaySqls extends UserAction<java.util.List<IMendixObject>>
{
	public TestTwoWaySqls(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		List<IMendixObject> resultMoList = new ArrayList<IMendixObject>();
		List<TwoSqlTestResult> resultList = new ArrayList<TwoSqlTestResult>();
		String absolutePath = Core.getConfiguration().getResourcesPath() + System.getProperty("file.separator") + "sql";
		List<File> files = findAllFile(absolutePath);
		for (File file : files) {
			TwoSqlTestResult twoSqlTestResult = new TwoSqlTestResult(getContext());
			twoSqlTestResult.setFilePath(file.getAbsolutePath());
			twoSqlTestResult.setRelativePath(file.getAbsolutePath().replace('\\', '/').replaceFirst("^.*/sql/", ""));
			twoSqlTestResult.setSqlStatement(readSql(file.getAbsolutePath()));
			resultMoList.add(twoSqlTestResult.getMendixObject());
			resultList.add(twoSqlTestResult);
		}

		for (TwoSqlTestResult result : resultList) {
			String extDataSourceName = TwoWaySqlExecutor.getExtDataSourceNameFromSql(result.getSqlStatement());
			if (extDataSourceName == null) {
				result.setDataSourceName("Internal");
				Core.dataStorage().executeWithConnection(getContext(), connection -> {
					doTestSQL(connection, result);
					return true;				
				});
			} else {
				result.setDataSourceName(extDataSourceName);
				DataSource ds = ExtDataSourceBinder.getExtDataSource(extDataSourceName);
				if (ds == null) {
					result.setTestStatus("09.NG (DataSource not found.)");
				} else {
					try (Connection connection = ds.getConnection()) {
						doTestSQL(connection, result);
					} catch (SQLException e) {
						result.setTestStatus("09.NG (Could not get connection.)");
						StringWriter sw = new StringWriter();
						PrintWriter pw = new PrintWriter(sw);
						e.printStackTrace(pw);
						result.setStackTrace(sw.toString());
					}
				}
			}
		}

		return resultMoList;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "TestTwoWaySqls";
	}

	// BEGIN EXTRA CODE
	public void doTestSQL(Connection con, TwoSqlTestResult result) {
		long startedTime = System.nanoTime();
		Boolean orgAutoCommit = null;
		try {
			orgAutoCommit = con.getAutoCommit();
			con.setAutoCommit(false);
			if (result.getRelativePath().lastIndexOf("CALL_") >= 0) {
				try (PreparedStatement stmt = con.prepareCall(result.getSqlStatement(getContext()))) {
					stmt.executeUpdate();
					result.setTestStatus("00.OK");
				}				
			} else {
				try (PreparedStatement stmt = con.prepareStatement(result.getSqlStatement(getContext()))) {
					if (result.getRelativePath().lastIndexOf("SEL_") >= 0) {
						try (ResultSet rset = stmt.executeQuery()) {
							Pattern p1 = Pattern.compile("--[ \t]*#(.*?)#");
							Matcher m1 = p1.matcher(result.getSqlStatement(getContext()));
							if (m1.find()) {
								result.setReturnEntityType(m1.group(1));
								if (rset.next()) {
									IMendixObject obj = Core.instantiate(getContext(), result.getReturnEntityType());
									Map<String, ? extends IMendixObjectMember<?>> momMap = obj.getMembers(getContext());
									Map<String, String> resultEntityMemberNames = new HashMap<String, String>();
									for (String key : momMap.keySet()) {
										resultEntityMemberNames.put(key.toLowerCase(), key);
									}
									ResultSetMetaData rmd = rset.getMetaData();
									int colCount = rmd.getColumnCount();
									for (int colIdx = 1; colIdx <= colCount; colIdx++) {
										String colName = rmd.getColumnLabel(colIdx);
										String entityMemberName = resultEntityMemberNames.get(colName.toLowerCase());
										if (entityMemberName != null) {
											obj.setValue(getContext(), entityMemberName, rset.getObject(colIdx));
										} else {
											throw new RuntimeException("Column '" + colName + "' doesn't exist in "
													+ result.getReturnEntityType());
										}
									}
									result.setTestStatus("00.OK");
								} else {
									result.setTestStatus("01.OK (but no records were selected.)");
								}
							} else {
								result.setTestStatus("02.OK (but there is no return entity type specified.)");
							}
						}
					} else {
						stmt.executeUpdate();
						result.setTestStatus("00.OK");
					}
				}
			}
		} catch (Exception e) {
			result.setTestStatus("09.NG");
			StringWriter sw = new StringWriter();
			PrintWriter pw = new PrintWriter(sw);
			e.printStackTrace(pw);
			result.setStackTrace(sw.toString());
		} finally {
			long finishedTime = System.nanoTime();
			result.setElapsedTime(finishedTime - startedTime);
			try {
				con.rollback();
			} catch (Exception e) {
			}
			if (orgAutoCommit != null) {
				try {
					con.setAutoCommit(orgAutoCommit);
				} catch (Exception e) {
				}
			}
		}
	}
	
	public static List<File> findAllFile(String absolutePath) {

		List<File> files = new ArrayList<>();

		Stack<File> stack = new Stack<>();
		stack.add(new File(absolutePath));
		while (!stack.isEmpty()) {
			File item = stack.pop();
			if (item.isFile())
				files.add(item);

			if (item.isDirectory()) {
				for (File child : item.listFiles())
					stack.push(child);
			}
		}

		return files;
	}

	public String readSql(String sqlFile) throws IOException {
		String sqlString;
		StringBuilder sql = new StringBuilder();
		try (InputStream is = new FileInputStream(sqlFile);
				BufferedReader br = new BufferedReader(new InputStreamReader(is))) {
			String lineData;
			while ((lineData = br.readLine()) != null) {
				sql.append(lineData + "\n");
			}

		} catch (IOException e) {
			e.printStackTrace();
		}
		sqlString = sql.toString();
		return sqlString;
	}

	// END EXTRA CODE
}
