// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twowaysql.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import twowaysql.implementation.TwoWaySqlExecutor;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Please use non-persistent Entity for search condition and search result.
 * 
 * About 2WaySQL , See also
 * http://dbflute.seasar.org/ja/manual/function/ormapper/outsidesql/about.html#twowaysql
 * However, due to the specification of MendixModeler, single quotes in 2 waySQL must be escaped with single quotes.
 * You have to use the parameter prefix 'pmb.'
 * 
 */
public class UpdateByTwoWaySql extends UserAction<java.lang.Long>
{
	private final java.lang.String TwoWaySqlFileName;
	private final IMendixObject Parameter;

	public UpdateByTwoWaySql(
		IContext context,
		java.lang.String _twoWaySqlFileName,
		IMendixObject _parameter
	)
	{
		super(context);
		this.TwoWaySqlFileName = _twoWaySqlFileName;
		this.Parameter = _parameter;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		TwoWaySqlExecutor twoWaySqlExecutor = new TwoWaySqlExecutor();
		int updateCount = twoWaySqlExecutor.updateByTwoWaySql(getContext(), TwoWaySqlFileName, Parameter);
        return (long)updateCount;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "UpdateByTwoWaySql";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
