// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoprofiler.proxies.constants;

import com.mendix.core.Core;

public final class Constants
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Constants() {}

	// These are the constants for the NanoProfiler module

	/**
	* If you set this to True, when the Mendix Runtime logger thread terminates abnormally, information about the cause of the error will be displayed in the 'LastErrorInfo' field of the NanoProfiler status.
	* Additional information:
	* The Mendix Runtime logger thread is the only thread responsible for log delivery, and if it terminates abnormally, not only will NanoProfiler stop working, but all logs will no longer be published, and the Java VM will then terminate abnormally with an OutOfMemoryError.
	*/
	public static boolean getMonitorRuntimeLoggerThreadDeath()
	{
		return (java.lang.Boolean)Core.getConfiguration().getConstantValue("NanoProfiler.MonitorRuntimeLoggerThreadDeath");
	}
}