// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package tinysqlstudio2.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the TinySqlStudio2 module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder initSearchDataForTableBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TinySqlStudio2.InitSearchDataForTable");
		return builder;
	}

	public static void initSearchDataForTable(IContext context)
	{
		initSearchDataForTableBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder initSearchDataForTxtBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TinySqlStudio2.InitSearchDataForTxt");
		return builder;
	}

	public static void initSearchDataForTxt(IContext context)
	{
		initSearchDataForTxtBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder initUpdateDataBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TinySqlStudio2.InitUpdateData");
		return builder;
	}

	public static void initUpdateData(IContext context)
	{
		initUpdateDataBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder outputCsvFileBuilder(
		tinysqlstudio2.proxies.SearchObject _sqlEntity
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TinySqlStudio2.OutputCsvFile");
		builder = builder.withParam("SqlEntity", _sqlEntity);
		return builder;
	}

	public static void outputCsvFile(
		IContext context,
		tinysqlstudio2.proxies.SearchObject _sqlEntity
	)
	{
		outputCsvFileBuilder(
				_sqlEntity
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder outputDataForTableBuilder(
		tinysqlstudio2.proxies.SearchObject _sqlEntity
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TinySqlStudio2.OutputDataForTable");
		builder = builder.withParam("SqlEntity", _sqlEntity);
		return builder;
	}

	public static void outputDataForTable(
		IContext context,
		tinysqlstudio2.proxies.SearchObject _sqlEntity
	)
	{
		outputDataForTableBuilder(
				_sqlEntity
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder outputDataForTxtBuilder(
		tinysqlstudio2.proxies.SearchObject _sqlEntity
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TinySqlStudio2.OutputDataForTxt");
		builder = builder.withParam("SqlEntity", _sqlEntity);
		return builder;
	}

	public static void outputDataForTxt(
		IContext context,
		tinysqlstudio2.proxies.SearchObject _sqlEntity
	)
	{
		outputDataForTxtBuilder(
				_sqlEntity
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder retrieveSummaryBuilder(
		java.lang.String _sql
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TinySqlStudio2.RetrieveSummary");
		builder = builder.withParam("Sql", _sql);
		return builder;
	}

	public static java.lang.String retrieveSummary(
		IContext context,
		java.lang.String _sql
	)
	{
		Object result = retrieveSummaryBuilder(
				_sql
			)
			.execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder retrieveUpdateBuilder(
		tinysqlstudio2.proxies.SearchObject _sqlEntity
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TinySqlStudio2.RetrieveUpdate");
		builder = builder.withParam("SqlEntity", _sqlEntity);
		return builder;
	}

	public static void retrieveUpdate(
		IContext context,
		tinysqlstudio2.proxies.SearchObject _sqlEntity
	)
	{
		retrieveUpdateBuilder(
				_sqlEntity
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder selectSqlBuilder(
		tinysqlstudio2.proxies.QueryTemplate _queryTemplate,
		tinysqlstudio2.proxies.SearchObject _searchObject
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TinySqlStudio2.SelectSql");
		builder = builder.withParam("QueryTemplate", _queryTemplate);
		builder = builder.withParam("SearchObject", _searchObject);
		return builder;
	}

	public static void selectSql(
		IContext context,
		tinysqlstudio2.proxies.QueryTemplate _queryTemplate,
		tinysqlstudio2.proxies.SearchObject _searchObject
	)
	{
		selectSqlBuilder(
				_queryTemplate,
				_searchObject
			)
			.execute(context);
	}
}
