// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the MyFirstModule module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_BatchFetchByTwoWaySQLTest_WithGetJoineeBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_BatchFetchByTwoWaySQLTest_WithGetJoinee");
		return builder;
	}

	public static void aCT_BatchFetchByTwoWaySQLTest_WithGetJoinee(IContext context)
	{
		aCT_BatchFetchByTwoWaySQLTest_WithGetJoineeBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_BatchFetchByTwoWaySQLTest_WithGotoLoopBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_BatchFetchByTwoWaySQLTest_WithGotoLoop");
		return builder;
	}

	public static void aCT_BatchFetchByTwoWaySQLTest_WithGotoLoop(IContext context)
	{
		aCT_BatchFetchByTwoWaySQLTest_WithGotoLoopBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_BatchFetchByTwoWaySQLTest_WithNPEBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_BatchFetchByTwoWaySQLTest_WithNPE");
		return builder;
	}

	public static void aCT_BatchFetchByTwoWaySQLTest_WithNPE(IContext context)
	{
		aCT_BatchFetchByTwoWaySQLTest_WithNPEBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_CallTestBuilder(
		myfirstmodule.proxies.EmployeePmb _employeePmb
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_CallTest");
		builder = builder.withParam("EmployeePmb", _employeePmb);
		return builder;
	}

	public static void aCT_CallTest(
		IContext context,
		myfirstmodule.proxies.EmployeePmb _employeePmb
	)
	{
		aCT_CallTestBuilder(
				_employeePmb
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_CreateEmpDataBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_CreateEmpData");
		return builder;
	}

	public static void aCT_CreateEmpData(IContext context)
	{
		aCT_CreateEmpDataBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_CursorLoopTestBuilder(
		myfirstmodule.proxies.EmployeePmb _employeePmb
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_CursorLoopTest");
		builder = builder.withParam("EmployeePmb", _employeePmb);
		return builder;
	}

	public static void aCT_CursorLoopTest(
		IContext context,
		myfirstmodule.proxies.EmployeePmb _employeePmb
	)
	{
		aCT_CursorLoopTestBuilder(
				_employeePmb
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_DeletePeByTwoWaySql_TESTBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_DeletePeByTwoWaySql_TEST");
		return builder;
	}

	public static void aCT_DeletePeByTwoWaySql_TEST(IContext context)
	{
		aCT_DeletePeByTwoWaySql_TESTBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_ExportCsvByTwoWaySqlTestBuilder(
		myfirstmodule.proxies.EmployeePmb _employeePmb
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_ExportCsvByTwoWaySqlTest");
		builder = builder.withParam("EmployeePmb", _employeePmb);
		return builder;
	}

	public static void aCT_ExportCsvByTwoWaySqlTest(
		IContext context,
		myfirstmodule.proxies.EmployeePmb _employeePmb
	)
	{
		aCT_ExportCsvByTwoWaySqlTestBuilder(
				_employeePmb
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_ExportCsvByTwoWaySqlTest_2Builder(
		myfirstmodule.proxies.EmployeePmb _employeePmb
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_ExportCsvByTwoWaySqlTest_2");
		builder = builder.withParam("EmployeePmb", _employeePmb);
		return builder;
	}

	public static void aCT_ExportCsvByTwoWaySqlTest_2(
		IContext context,
		myfirstmodule.proxies.EmployeePmb _employeePmb
	)
	{
		aCT_ExportCsvByTwoWaySqlTest_2Builder(
				_employeePmb
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_ExtDsExportCsvTestBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_ExtDsExportCsvTest");
		return builder;
	}

	public static void aCT_ExtDsExportCsvTest(IContext context)
	{
		aCT_ExtDsExportCsvTestBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_ExtDsInsertSelectTestBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_ExtDsInsertSelectTest");
		return builder;
	}

	public static void aCT_ExtDsInsertSelectTest(IContext context)
	{
		aCT_ExtDsInsertSelectTestBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_ExtDsRetrieveTestBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_ExtDsRetrieveTest");
		return builder;
	}

	public static void aCT_ExtDsRetrieveTest(IContext context)
	{
		aCT_ExtDsRetrieveTestBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_ExtDsUpdateTestBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_ExtDsUpdateTest");
		return builder;
	}

	public static void aCT_ExtDsUpdateTest(IContext context)
	{
		aCT_ExtDsUpdateTestBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_InsertSelectByTwoWaySql_TESTBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_InsertSelectByTwoWaySql_TEST");
		return builder;
	}

	public static void aCT_InsertSelectByTwoWaySql_TEST(IContext context)
	{
		aCT_InsertSelectByTwoWaySql_TESTBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_ReDispTwoWaySqlTestPageBuilder(
		myfirstmodule.proxies.EmployeePmb _employeePmb
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_ReDispTwoWaySqlTestPage");
		builder = builder.withParam("EmployeePmb", _employeePmb);
		return builder;
	}

	public static void aCT_ReDispTwoWaySqlTestPage(
		IContext context,
		myfirstmodule.proxies.EmployeePmb _employeePmb
	)
	{
		aCT_ReDispTwoWaySqlTestPageBuilder(
				_employeePmb
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TestRetrievePeByTwoWaySqlBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_TestRetrievePeByTwoWaySql");
		return builder;
	}

	public static void aCT_TestRetrievePeByTwoWaySql(IContext context)
	{
		aCT_TestRetrievePeByTwoWaySqlBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_UpdateTestBuilder(
		myfirstmodule.proxies.EmployeePmb _employeePmb
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_UpdateTest");
		builder = builder.withParam("EmployeePmb", _employeePmb);
		return builder;
	}

	public static void aCT_UpdateTest(
		IContext context,
		myfirstmodule.proxies.EmployeePmb _employeePmb
	)
	{
		aCT_UpdateTestBuilder(
				_employeePmb
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aSU_testBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ASU_test");
		return builder;
	}

	public static boolean aSU_test(IContext context)
	{
		Object result = aSU_testBuilder().execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder cB_BeforeBachCommitBuilder(
		java.util.List<myfirstmodule.proxies.Employee_2> _insertEntityList
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.CB_BeforeBachCommit");
		builder = builder.withParam("InsertEntityList", _insertEntityList);
		return builder;
	}

	public static void cB_BeforeBachCommit(
		IContext context,
		java.util.List<myfirstmodule.proxies.Employee_2> _insertEntityList
	)
	{
		cB_BeforeBachCommitBuilder(
				_insertEntityList
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder cB_CursorLoopTestBuilder(
		myfirstmodule.proxies.EmployeePmb _employeePmb,
		system.proxies.User _user,
		java.util.List<myfirstmodule.proxies.EmployeeTwoWaySqlResult> _twoWaySqlResultList,
		myfirstmodule.proxies.EmployeeTwoWaySqlResult _currentObject
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.CB_CursorLoopTest");
		builder = builder.withParam("EmployeePmb", _employeePmb);
		builder = builder.withParam("User", _user);
		builder = builder.withParam("TwoWaySqlResultList", _twoWaySqlResultList);
		builder = builder.withParam("CurrentObject", _currentObject);
		return builder;
	}

	public static void cB_CursorLoopTest(
		IContext context,
		myfirstmodule.proxies.EmployeePmb _employeePmb,
		system.proxies.User _user,
		java.util.List<myfirstmodule.proxies.EmployeeTwoWaySqlResult> _twoWaySqlResultList,
		myfirstmodule.proxies.EmployeeTwoWaySqlResult _currentObject
	)
	{
		cB_CursorLoopTestBuilder(
				_employeePmb,
				_user,
				_twoWaySqlResultList,
				_currentObject
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_TwoWaySqlResultBuilder(
		myfirstmodule.proxies.EmployeePmb _employeePmb
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.DS_TwoWaySqlResult");
		builder = builder.withParam("EmployeePmb", _employeePmb);
		return builder;
	}

	public static java.util.List<myfirstmodule.proxies.EmployeeTwoWaySqlResult> dS_TwoWaySqlResult(
		IContext context,
		myfirstmodule.proxies.EmployeePmb _employeePmb
	)
	{
		Object result = dS_TwoWaySqlResultBuilder(
				_employeePmb
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> myfirstmodule.proxies.EmployeeTwoWaySqlResult.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder iVK_EmployeeEdit_ByTwoWaySqlResultBuilder(
		myfirstmodule.proxies.EmployeeTwoWaySqlResult _employeeTwoWaySqlResult
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.IVK_EmployeeEdit_ByTwoWaySqlResult");
		builder = builder.withParam("EmployeeTwoWaySqlResult", _employeeTwoWaySqlResult);
		return builder;
	}

	public static void iVK_EmployeeEdit_ByTwoWaySqlResult(
		IContext context,
		myfirstmodule.proxies.EmployeeTwoWaySqlResult _employeeTwoWaySqlResult
	)
	{
		iVK_EmployeeEdit_ByTwoWaySqlResultBuilder(
				_employeeTwoWaySqlResult
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder nAV_DispTwoWaySqlSamplePageBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.NAV_DispTwoWaySqlSamplePage");
		return builder;
	}

	public static void nAV_DispTwoWaySqlSamplePage(IContext context)
	{
		nAV_DispTwoWaySqlSamplePageBuilder().execute(context);
	}
}
