// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package tinysqlstudio2.actions;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Execute the Sql statement and return the number of search results
 */
public class RetrieveCountAdvanced extends UserAction<java.lang.Long>
{
	private final java.lang.String Sql;

	public RetrieveCountAdvanced(
		IContext context,
		java.lang.String _sql
	)
	{
		super(context);
		this.Sql = _sql;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		logger.info("executeAction: " + this.Sql);
		return Core.dataStorage().executeWithConnection(connection -> {
			try {
				PreparedStatement stmt = connection
						.prepareStatement("select count(*) from (" + this.Sql.replaceAll(";", "") + ") as cntE");
				ResultSet rset = stmt.executeQuery();

				if (!rset.next()) {
					return 0l;
				}

				return rset.getLong(1);

			} catch (SQLException e) {
				logger.error("Failed to execute sql statement: " + e.getMessage());
				throw new MendixRuntimeException(e);
			}
		});
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "RetrieveCountAdvanced";
	}

	// BEGIN EXTRA CODE
	private final ILogNode logger = Core.getLogger(this.getClass().getName());
	// END EXTRA CODE
}
