// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package appcloudservices.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the AppCloudServices module
	public static boolean checkUserRolesRemoved(IContext context, system.proxies.User _user)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("User", _user == null ? null : _user.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("AppCloudServices.CheckUserRolesRemoved").withParams(params).execute(context);
	}
	public static void inviteUserToApp(IContext context, java.lang.String _inviteeEmailAddress, system.proxies.UserRole _userRole, java.lang.String _inviterEmailAddress)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("InviteeEmailAddress", _inviteeEmailAddress);
		params.put("UserRole", _userRole == null ? null : _userRole.getMendixObject());
		params.put("InviterEmailAddress", _inviterEmailAddress);
		Core.microflowCall("AppCloudServices.InviteUserToApp").withParams(params).execute(context);
	}
	public static void invokeOnFirstLoginAppCloudUser(IContext context, java.lang.String _userIdentity)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("UserIdentity", _userIdentity);
		Core.microflowCall("AppCloudServices.InvokeOnFirstLoginAppCloudUser").withParams(params).execute(context);
	}
	public static void invokeOnNonFirstLoginAppCloudUser(IContext context, system.proxies.User _user)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("User", _user == null ? null : _user.getMendixObject());
		Core.microflowCall("AppCloudServices.InvokeOnNonFirstLoginAppCloudUser").withParams(params).execute(context);
	}
	public static boolean provisionAsAppCloudUser(IContext context, system.proxies.User _userAccount, java.lang.String _userIdentity)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("UserAccount", _userAccount == null ? null : _userAccount.getMendixObject());
		params.put("UserIdentity", _userIdentity);
		return (java.lang.Boolean) Core.microflowCall("AppCloudServices.ProvisionAsAppCloudUser").withParams(params).execute(context);
	}
	public static void refreshUserPermissions(IContext context, java.lang.String _openId)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("OpenId", _openId);
		Core.microflowCall("AppCloudServices.RefreshUserPermissions").withParams(params).execute(context);
	}
	public static profileservice.proxies.UserProfile retrieveUserProfile(IContext context, java.lang.String _userIdentity)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("UserIdentity", _userIdentity);
		IMendixObject result = (IMendixObject)Core.microflowCall("AppCloudServices.RetrieveUserProfile").withParams(params).execute(context);
		return result == null ? null : profileservice.proxies.UserProfile.initialize(context, result);
	}
	public static boolean retrieveUserRoles(IContext context, system.proxies.User _user)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("User", _user == null ? null : _user.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("AppCloudServices.RetrieveUserRoles").withParams(params).execute(context);
	}
	public static boolean startAppCloudServices(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.Boolean) Core.microflowCall("AppCloudServices.StartAppCloudServices").withParams(params).execute(context);
	}
}