// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

/**
 * SaferOQLの検索条件を渡すための非永続エンティティ
 */
public class EmployeeBatchFetchRel implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject employeeBatchFetchRelMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.EmployeeBatchFetchRel";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		IdValue("IdValue"),
		DeptName("DeptName");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EmployeeBatchFetchRel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected EmployeeBatchFetchRel(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject employeeBatchFetchRelMendixObject)
	{
		if (employeeBatchFetchRelMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!employeeBatchFetchRelMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.employeeBatchFetchRelMendixObject = employeeBatchFetchRelMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.EmployeeBatchFetchRel initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.EmployeeBatchFetchRel(context, mendixObject);
	}

	public static myfirstmodule.proxies.EmployeeBatchFetchRel load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.EmployeeBatchFetchRel.initialize(context, mendixObject);
	}

	/**
	 * @return value of IdValue
	 */
	public final java.lang.Long getIdValue()
	{
		return getIdValue(getContext());
	}

	/**
	 * @param context
	 * @return value of IdValue
	 */
	public final java.lang.Long getIdValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.IdValue.toString());
	}

	/**
	 * Set value of IdValue
	 * @param idvalue
	 */
	public final void setIdValue(java.lang.Long idvalue)
	{
		setIdValue(getContext(), idvalue);
	}

	/**
	 * Set value of IdValue
	 * @param context
	 * @param idvalue
	 */
	public final void setIdValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long idvalue)
	{
		getMendixObject().setValue(context, MemberNames.IdValue.toString(), idvalue);
	}

	/**
	 * @return value of DeptName
	 */
	public final java.lang.String getDeptName()
	{
		return getDeptName(getContext());
	}

	/**
	 * @param context
	 * @return value of DeptName
	 */
	public final java.lang.String getDeptName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DeptName.toString());
	}

	/**
	 * Set value of DeptName
	 * @param deptname
	 */
	public final void setDeptName(java.lang.String deptname)
	{
		setDeptName(getContext(), deptname);
	}

	/**
	 * Set value of DeptName
	 * @param context
	 * @param deptname
	 */
	public final void setDeptName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String deptname)
	{
		getMendixObject().setValue(context, MemberNames.DeptName.toString(), deptname);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return employeeBatchFetchRelMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.EmployeeBatchFetchRel that = (myfirstmodule.proxies.EmployeeBatchFetchRel) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
