// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

/**
 * 2WaySQLの結果を受け取るための非永続エンティティ
 */
public class EmployeeTwoWaySqlResult implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject employeeTwoWaySqlResultMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.EmployeeTwoWaySqlResult";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Address("Address"),
		BirthDate("BirthDate"),
		IsHoge("IsHoge"),
		DecVal("DecVal"),
		IntVal("IntVal"),
		IdValue("IdValue"),
		Department("Department");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EmployeeTwoWaySqlResult(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected EmployeeTwoWaySqlResult(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject employeeTwoWaySqlResultMendixObject)
	{
		if (employeeTwoWaySqlResultMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!employeeTwoWaySqlResultMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.employeeTwoWaySqlResultMendixObject = employeeTwoWaySqlResultMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.EmployeeTwoWaySqlResult initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.EmployeeTwoWaySqlResult(context, mendixObject);
	}

	public static myfirstmodule.proxies.EmployeeTwoWaySqlResult load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.EmployeeTwoWaySqlResult.initialize(context, mendixObject);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Address
	 */
	public final java.lang.String getAddress()
	{
		return getAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of Address
	 */
	public final java.lang.String getAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Address.toString());
	}

	/**
	 * Set value of Address
	 * @param address
	 */
	public final void setAddress(java.lang.String address)
	{
		setAddress(getContext(), address);
	}

	/**
	 * Set value of Address
	 * @param context
	 * @param address
	 */
	public final void setAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String address)
	{
		getMendixObject().setValue(context, MemberNames.Address.toString(), address);
	}

	/**
	 * @return value of BirthDate
	 */
	public final java.util.Date getBirthDate()
	{
		return getBirthDate(getContext());
	}

	/**
	 * @param context
	 * @return value of BirthDate
	 */
	public final java.util.Date getBirthDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.BirthDate.toString());
	}

	/**
	 * Set value of BirthDate
	 * @param birthdate
	 */
	public final void setBirthDate(java.util.Date birthdate)
	{
		setBirthDate(getContext(), birthdate);
	}

	/**
	 * Set value of BirthDate
	 * @param context
	 * @param birthdate
	 */
	public final void setBirthDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date birthdate)
	{
		getMendixObject().setValue(context, MemberNames.BirthDate.toString(), birthdate);
	}

	/**
	 * @return value of IsHoge
	 */
	public final java.lang.Boolean getIsHoge()
	{
		return getIsHoge(getContext());
	}

	/**
	 * @param context
	 * @return value of IsHoge
	 */
	public final java.lang.Boolean getIsHoge(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsHoge.toString());
	}

	/**
	 * Set value of IsHoge
	 * @param ishoge
	 */
	public final void setIsHoge(java.lang.Boolean ishoge)
	{
		setIsHoge(getContext(), ishoge);
	}

	/**
	 * Set value of IsHoge
	 * @param context
	 * @param ishoge
	 */
	public final void setIsHoge(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean ishoge)
	{
		getMendixObject().setValue(context, MemberNames.IsHoge.toString(), ishoge);
	}

	/**
	 * @return value of DecVal
	 */
	public final java.math.BigDecimal getDecVal()
	{
		return getDecVal(getContext());
	}

	/**
	 * @param context
	 * @return value of DecVal
	 */
	public final java.math.BigDecimal getDecVal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.DecVal.toString());
	}

	/**
	 * Set value of DecVal
	 * @param decval
	 */
	public final void setDecVal(java.math.BigDecimal decval)
	{
		setDecVal(getContext(), decval);
	}

	/**
	 * Set value of DecVal
	 * @param context
	 * @param decval
	 */
	public final void setDecVal(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal decval)
	{
		getMendixObject().setValue(context, MemberNames.DecVal.toString(), decval);
	}

	/**
	 * @return value of IntVal
	 */
	public final java.lang.Integer getIntVal()
	{
		return getIntVal(getContext());
	}

	/**
	 * @param context
	 * @return value of IntVal
	 */
	public final java.lang.Integer getIntVal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.IntVal.toString());
	}

	/**
	 * Set value of IntVal
	 * @param intval
	 */
	public final void setIntVal(java.lang.Integer intval)
	{
		setIntVal(getContext(), intval);
	}

	/**
	 * Set value of IntVal
	 * @param context
	 * @param intval
	 */
	public final void setIntVal(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer intval)
	{
		getMendixObject().setValue(context, MemberNames.IntVal.toString(), intval);
	}

	/**
	 * @return value of IdValue
	 */
	public final java.lang.Long getIdValue()
	{
		return getIdValue(getContext());
	}

	/**
	 * @param context
	 * @return value of IdValue
	 */
	public final java.lang.Long getIdValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.IdValue.toString());
	}

	/**
	 * Set value of IdValue
	 * @param idvalue
	 */
	public final void setIdValue(java.lang.Long idvalue)
	{
		setIdValue(getContext(), idvalue);
	}

	/**
	 * Set value of IdValue
	 * @param context
	 * @param idvalue
	 */
	public final void setIdValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long idvalue)
	{
		getMendixObject().setValue(context, MemberNames.IdValue.toString(), idvalue);
	}

	/**
	 * @return value of Department
	 */
	public final java.lang.String getDepartment()
	{
		return getDepartment(getContext());
	}

	/**
	 * @param context
	 * @return value of Department
	 */
	public final java.lang.String getDepartment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Department.toString());
	}

	/**
	 * Set value of Department
	 * @param department
	 */
	public final void setDepartment(java.lang.String department)
	{
		setDepartment(getContext(), department);
	}

	/**
	 * Set value of Department
	 * @param context
	 * @param department
	 */
	public final void setDepartment(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String department)
	{
		getMendixObject().setValue(context, MemberNames.Department.toString(), department);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return employeeTwoWaySqlResultMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.EmployeeTwoWaySqlResult that = (myfirstmodule.proxies.EmployeeTwoWaySqlResult) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
