// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class TwoWaySqlAutoTest_DataGrid extends system.proxies.Paging
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.TwoWaySqlAutoTest_DataGrid";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FilePath("FilePath"),
		TestStatus("TestStatus"),
		TestResult("TestResult"),
		PageNumber("PageNumber"),
		IsSortable("IsSortable"),
		SortAttribute("SortAttribute"),
		SortAscending("SortAscending"),
		HasMoreData("HasMoreData");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TwoWaySqlAutoTest_DataGrid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TwoWaySqlAutoTest_DataGrid(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject twoWaySqlAutoTest_DataGridMendixObject)
	{
		super(context, twoWaySqlAutoTest_DataGridMendixObject);
		if (!twoWaySqlAutoTest_DataGridMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.TwoWaySqlAutoTest_DataGrid initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.TwoWaySqlAutoTest_DataGrid(context, mendixObject);
	}

	public static myfirstmodule.proxies.TwoWaySqlAutoTest_DataGrid load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.TwoWaySqlAutoTest_DataGrid.initialize(context, mendixObject);
	}

	/**
	 * @return value of FilePath
	 */
	public final java.lang.String getFilePath()
	{
		return getFilePath(getContext());
	}

	/**
	 * @param context
	 * @return value of FilePath
	 */
	public final java.lang.String getFilePath(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FilePath.toString());
	}

	/**
	 * Set value of FilePath
	 * @param filepath
	 */
	public final void setFilePath(java.lang.String filepath)
	{
		setFilePath(getContext(), filepath);
	}

	/**
	 * Set value of FilePath
	 * @param context
	 * @param filepath
	 */
	public final void setFilePath(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String filepath)
	{
		getMendixObject().setValue(context, MemberNames.FilePath.toString(), filepath);
	}

	/**
	 * @return value of TestStatus
	 */
	public final java.lang.String getTestStatus()
	{
		return getTestStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of TestStatus
	 */
	public final java.lang.String getTestStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TestStatus.toString());
	}

	/**
	 * Set value of TestStatus
	 * @param teststatus
	 */
	public final void setTestStatus(java.lang.String teststatus)
	{
		setTestStatus(getContext(), teststatus);
	}

	/**
	 * Set value of TestStatus
	 * @param context
	 * @param teststatus
	 */
	public final void setTestStatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String teststatus)
	{
		getMendixObject().setValue(context, MemberNames.TestStatus.toString(), teststatus);
	}

	/**
	 * @return value of TestResult
	 */
	public final java.lang.String getTestResult()
	{
		return getTestResult(getContext());
	}

	/**
	 * @param context
	 * @return value of TestResult
	 */
	public final java.lang.String getTestResult(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TestResult.toString());
	}

	/**
	 * Set value of TestResult
	 * @param testresult
	 */
	public final void setTestResult(java.lang.String testresult)
	{
		setTestResult(getContext(), testresult);
	}

	/**
	 * Set value of TestResult
	 * @param context
	 * @param testresult
	 */
	public final void setTestResult(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String testresult)
	{
		getMendixObject().setValue(context, MemberNames.TestResult.toString(), testresult);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.TwoWaySqlAutoTest_DataGrid that = (myfirstmodule.proxies.TwoWaySqlAutoTest_DataGrid) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
