// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package twowaysql.proxies.constants;

import com.mendix.core.Core;

public final class Constants
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Constants() {}

	// These are the constants for the TwoWaySQL module

	/**
	* A constant representing the date format for the ExportCsvByTwoWaySql action. It is used when no date format is specified during the execution of ExportCsvByTwoWaySql.
	*/
	public static java.lang.String getDateTimeFormat()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("TwoWaySQL.DateTimeFormat");
	}

	/**
	* Specify the default batch size for batch commit.
	*/
	public static java.lang.Long getDEFAULT_BATCH_COMMIT_SIZE()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("TwoWaySQL.DEFAULT_BATCH_COMMIT_SIZE");
	}

	/**
	* Specify the default cache size of the Joinee cache.
	*/
	public static java.lang.Long getDEFAULT_JOINEE_CACHE_SIZE()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("TwoWaySQL.DEFAULT_JOINEE_CACHE_SIZE");
	}

	/**
	* No options for external data sources.
	*/
	public static java.lang.Long getEXDS_NO_OPTION()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("TwoWaySQL.EXDS_NO_OPTION");
	}

	/**
	* This option prevents the system from adjusting SQL parameters of the "Date and Time" type (with time zone) to UTC when converting them to `java.sql.Timestamp` (without time zone).
	* By default, a "Date and Time" parameter value of 9:00 JST would be converted to 0:00; enabling this option ensures it remains 9:00.
	* As this setting applies to parameters, it affects parameters used in `WHERE`, `INSERT`, or `UPDATE` clauses within the "AddDateTimeParameter" action.
	* 
	* If the external data source is a Mendix database, UTC time without a time zone is already stored, so this option is not required.
	* In other cases, please configure this setting according to your environment.
	*/
	public static java.lang.Long getEXDS_WO_PRAM_TZ_ADJST()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("TwoWaySQL.EXDS_WO_PRAM_TZ_ADJST");
	}

	/**
	* When converting a `java.sql.Timestamp` (timezone-agnostic) obtained from an external data source query into a Mendix Runtime "Date and Time" attribute (timezone-aware), this option treats the retrieved timestamp as already adjusted to the execution environment's timezone, thereby preventing any additional UTC-based timezone adjustment.
	* This option is not required if the external data source is the Mendix database itself.
	* In other cases, please configure this setting according to your environment.
	* 
	* By default (without this option), if the target timezone is JST and the SQL result's `java.sql.Timestamp` is 00:00, the output value becomes 09:00 JST; however, enabling this option results in 00:00 JST.
	* *Note: The "target timezone" here refers to the VM execution environment's timezone for `RetrieveByTwoWaySql`, and the timezone specified in the `CsvFormat` for `ExportCsvByTwoWaySql`.
	* 
	* Since this setting applies to the conversion of SQL execution results, it only affects data storage into entity "Date and Time" attributes and CSV output operations. It does not affect cases where date/time fields from the database are converted directly to strings within the SQL statement itself. If you convert date/time fields to strings within the SQL, please account for timezone adjustments at that stage.
	*/
	public static java.lang.Long getEXDS_WO_RSLT_TZ_ADJST()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("TwoWaySQL.EXDS_WO_RSLT_TZ_ADJST");
	}

	/**
	* Cardinality value to determine whether to use JOINEE CACHE. A percentage value from 1 to 100, where 100 means that all values are unique. Cache is enabled when the actual data Cardinality value is less than or equal to the specified value.
	*/
	public static java.lang.Long getJOINEE_CACHE_USE_THRESHOLD_CARDINALITY()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("TwoWaySQL.JOINEE_CACHE_USE_THRESHOLD_CARDINALITY");
	}

	public static java.lang.Long getSlowQueryThresholdMillis()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("TwoWaySQL.SlowQueryThresholdMillis");
	}
}