// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package twowaysql.proxies.constants;

import com.mendix.core.Core;

public final class Constants
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Constants() {}

	// These are the constants for the TwoWaySQL module

	/**
	* ExportCsvByTwoWaySqlの日付フォーマットを示すConstant。日付フォーマットの指定がない場合に使用する。
	*/
	public static java.lang.String getDateTimeFormat()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("TwoWaySQL.DateTimeFormat");
	}

	/**
	* Specify the default batch size for batch commit.
	*/
	public static java.lang.Long getDEFAULT_BATCH_COMMIT_SIZE()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("TwoWaySQL.DEFAULT_BATCH_COMMIT_SIZE");
	}

	/**
	* Specify the default cache size of the Joinee cache.
	*/
	public static java.lang.Long getDEFAULT_JOINEE_CACHE_SIZE()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("TwoWaySQL.DEFAULT_JOINEE_CACHE_SIZE");
	}

	/**
	* 外部データソースに対するオプション無し
	*/
	public static java.lang.Long getEXDS_NO_OPTION()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("TwoWaySQL.EXDS_NO_OPTION");
	}

	/**
	* 外部データソースで動かすSQLパラメータをData and Time型(タイムゾーン有)からjava.sql.Timestamp(タイムゾーン無)へ変換する際にUTC時刻への調整を行わないようにします。
	* デフォストではSQLパラメータのData and Timeは例えば9:00JSTなら0:00になりますが。このオプションを付けると9:00となります。
	* パラメータへの指定なので、影響するのはAddDateTimeParameterアクションでのWhere句やInsert/Update句へのパタメータです。
	* 
	* 外部データソースがMendixのDBである場合はタイムゾーン無しのUTC時刻が保管されているためこのオプションは指定不要です。
	* その他の場合は環境に合わせて指定して下さい。
	* 
	*/
	public static java.lang.Long getEXDS_WO_PRAM_TZ_ADJST()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("TwoWaySQL.EXDS_WO_PRAM_TZ_ADJST");
	}

	/**
	* 外部データソースで動かすSQL実行結果のjava.sql.Timestamp(タイムゾーン無)からData and Time型(タイムゾーン有)へ変換する際に、取得したjava.sql.Timestampが実行環境のタイムゾーンへの時刻調整済みであるとみなし、UTC相対での時刻調整を行わないようにします。
	* 外部データソースがMendixのDBである場合は本オプションは指定不要です。
	* その他の場合は環境に合わせて指定して下さい。
	* 
	* デフォルト(指定なし)ではターゲットタイムゾーンがJSTであればSQL実行結果のava.sql.Timestampが0:00なら出力値は9:00JSTになりますが、このオプションを付けると0:00JSTとなります。
	* ※ここでのターゲットタイムゾーンはRetrieveByTwoWaySqlであればVMの実行環境のタイムゾーンで、ExportCsvByTwoWaySqlであればCsvFormatで指定されたタイムゾーンです。
	* 
	* SQL実行結果変換への指定なので影響するのはEntityのData and Time型の項目へのストア時とCSV出力時のみです。SQL文上で直接DB上の日時項目を文字列に変換する場合は影響しません。SQL上で日時項目を文字列に変換する場合はそこでタイムゾーン調整を考慮して下さい。
	*/
	public static java.lang.Long getEXDS_WO_RSLT_TZ_ADJST()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("TwoWaySQL.EXDS_WO_RSLT_TZ_ADJST");
	}

	/**
	* Cardinality value to determine whether to use JOINEE CACHE. A percentage value from 1 to 100, where 100 means that all values are unique. Cache is enabled when the actual data Cardinality value is less than or equal to the specified value.
	*/
	public static java.lang.Long getJOINEE_CACHE_USE_THRESHOLD_CARDINALITY()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("TwoWaySQL.JOINEE_CACHE_USE_THRESHOLD_CARDINALITY");
	}

	public static java.lang.Long getSlowQueryThresholdMillis()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("TwoWaySQL.SlowQueryThresholdMillis");
	}
}