// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package tinysqlstudio2.proxies;

public class SearchObject implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject searchObjectMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TinySqlStudio2.SearchObject";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Sql("Sql"),
		Header("Header"),
		Data("Data"),
		PageNo("PageNo"),
		TotalCount("TotalCount"),
		PagingSql("PagingSql"),
		DisplayCount("DisplayCount");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SearchObject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected SearchObject(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject searchObjectMendixObject)
	{
		if (searchObjectMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!searchObjectMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.searchObjectMendixObject = searchObjectMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static tinysqlstudio2.proxies.SearchObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new tinysqlstudio2.proxies.SearchObject(context, mendixObject);
	}

	public static tinysqlstudio2.proxies.SearchObject load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return tinysqlstudio2.proxies.SearchObject.initialize(context, mendixObject);
	}

	/**
	 * @return value of Sql
	 */
	public final java.lang.String getSql()
	{
		return getSql(getContext());
	}

	/**
	 * @param context
	 * @return value of Sql
	 */
	public final java.lang.String getSql(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Sql.toString());
	}

	/**
	 * Set value of Sql
	 * @param sql
	 */
	public final void setSql(java.lang.String sql)
	{
		setSql(getContext(), sql);
	}

	/**
	 * Set value of Sql
	 * @param context
	 * @param sql
	 */
	public final void setSql(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sql)
	{
		getMendixObject().setValue(context, MemberNames.Sql.toString(), sql);
	}

	/**
	 * @return value of Header
	 */
	public final java.lang.String getHeader()
	{
		return getHeader(getContext());
	}

	/**
	 * @param context
	 * @return value of Header
	 */
	public final java.lang.String getHeader(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Header.toString());
	}

	/**
	 * Set value of Header
	 * @param header
	 */
	public final void setHeader(java.lang.String header)
	{
		setHeader(getContext(), header);
	}

	/**
	 * Set value of Header
	 * @param context
	 * @param header
	 */
	public final void setHeader(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String header)
	{
		getMendixObject().setValue(context, MemberNames.Header.toString(), header);
	}

	/**
	 * @return value of Data
	 */
	public final java.lang.String getData()
	{
		return getData(getContext());
	}

	/**
	 * @param context
	 * @return value of Data
	 */
	public final java.lang.String getData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Data.toString());
	}

	/**
	 * Set value of Data
	 * @param data
	 */
	public final void setData(java.lang.String data)
	{
		setData(getContext(), data);
	}

	/**
	 * Set value of Data
	 * @param context
	 * @param data
	 */
	public final void setData(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String data)
	{
		getMendixObject().setValue(context, MemberNames.Data.toString(), data);
	}

	/**
	 * @return value of PageNo
	 */
	public final java.lang.Integer getPageNo()
	{
		return getPageNo(getContext());
	}

	/**
	 * @param context
	 * @return value of PageNo
	 */
	public final java.lang.Integer getPageNo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.PageNo.toString());
	}

	/**
	 * Set value of PageNo
	 * @param pageno
	 */
	public final void setPageNo(java.lang.Integer pageno)
	{
		setPageNo(getContext(), pageno);
	}

	/**
	 * Set value of PageNo
	 * @param context
	 * @param pageno
	 */
	public final void setPageNo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer pageno)
	{
		getMendixObject().setValue(context, MemberNames.PageNo.toString(), pageno);
	}

	/**
	 * @return value of TotalCount
	 */
	public final java.lang.Integer getTotalCount()
	{
		return getTotalCount(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalCount
	 */
	public final java.lang.Integer getTotalCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TotalCount.toString());
	}

	/**
	 * Set value of TotalCount
	 * @param totalcount
	 */
	public final void setTotalCount(java.lang.Integer totalcount)
	{
		setTotalCount(getContext(), totalcount);
	}

	/**
	 * Set value of TotalCount
	 * @param context
	 * @param totalcount
	 */
	public final void setTotalCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer totalcount)
	{
		getMendixObject().setValue(context, MemberNames.TotalCount.toString(), totalcount);
	}

	/**
	 * @return value of PagingSql
	 */
	public final java.lang.String getPagingSql()
	{
		return getPagingSql(getContext());
	}

	/**
	 * @param context
	 * @return value of PagingSql
	 */
	public final java.lang.String getPagingSql(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PagingSql.toString());
	}

	/**
	 * Set value of PagingSql
	 * @param pagingsql
	 */
	public final void setPagingSql(java.lang.String pagingsql)
	{
		setPagingSql(getContext(), pagingsql);
	}

	/**
	 * Set value of PagingSql
	 * @param context
	 * @param pagingsql
	 */
	public final void setPagingSql(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String pagingsql)
	{
		getMendixObject().setValue(context, MemberNames.PagingSql.toString(), pagingsql);
	}

	/**
	 * @return value of DisplayCount
	 */
	public final java.lang.Integer getDisplayCount()
	{
		return getDisplayCount(getContext());
	}

	/**
	 * @param context
	 * @return value of DisplayCount
	 */
	public final java.lang.Integer getDisplayCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.DisplayCount.toString());
	}

	/**
	 * Set value of DisplayCount
	 * @param displaycount
	 */
	public final void setDisplayCount(java.lang.Integer displaycount)
	{
		setDisplayCount(getContext(), displaycount);
	}

	/**
	 * Set value of DisplayCount
	 * @param context
	 * @param displaycount
	 */
	public final void setDisplayCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer displaycount)
	{
		getMendixObject().setValue(context, MemberNames.DisplayCount.toString(), displaycount);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return searchObjectMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final tinysqlstudio2.proxies.SearchObject that = (tinysqlstudio2.proxies.SearchObject) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
