// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("a586744e-26cb-43d6-ad25-621d3efe5150"),
	startsWith("ed891aa5-f09f-4088-9519-1aafece9afc2"),
	endsWith("afae2408-952e-49b9-a7f5-5a0f9a14261d"),
	between("ab7971d8-ff10-4018-9b8d-7129ab7999b5"),
	greater("33eb2143-c4d5-4674-b413-2943bee205c8"),
	greaterEqual("06c9d83f-078b-4ec8-a542-b380b1eeb828"),
	equal("67206fdf-206b-400f-baa6-c67d96a7b88c"),
	notEqual("cb67dfe0-4b0a-48cb-9060-e6e589f444b5"),
	smaller("92c071dd-10af-48cc-ad94-9a200cd4d6ab"),
	smallerEqual("bb075c87-211d-4ed7-94c9-6e271fd97e56"),
	empty("d44f9daa-37c7-488d-ae0e-253a6649643c"),
	notEmpty("6a63a16a-23e2-4278-affb-8bf64490200e");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
