// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package nanoprofiler.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import nanoprofiler.implementation.NanoProfiler;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Output profile results to loger as DEBUG.
 */
public class LogNanoProfileAsDebug extends UserAction<java.lang.Void>
{
	private final java.lang.String handle;
	private final java.lang.Boolean stopNanoProfilerAfterLog;

	public LogNanoProfileAsDebug(
		IContext context,
		java.lang.String _handle,
		java.lang.Boolean _stopNanoProfilerAfterLog
	)
	{
		super(context);
		this.handle = _handle;
		this.stopNanoProfilerAfterLog = _stopNanoProfilerAfterLog;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (handle != null) {
			NanoProfiler nanoProfiler = NanoProfiler.getProfilerMap().get(handle);
			if (nanoProfiler != null) {
				try {
					String report = nanoProfiler.report(getContext());
					logger.debug(report);
				} finally {
					if (stopNanoProfilerAfterLog) {
						NanoProfiler.getProfilerMap().remove(handle);
					}
				}
			}
		}
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "LogNanoProfileAsDebug";
	}

	// BEGIN EXTRA CODE
	private static ILogNode logger = Core.getLogger(NanoProfiler.class.getSimpleName());
	// END EXTRA CODE
}
