// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package nanoprofiler.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import nanoprofiler.implementation.NanoProfiler;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Stop the profiler.
 */
public class StopNanoProfiler extends UserAction<java.lang.Void>
{
	private final java.lang.String handle;

	public StopNanoProfiler(
		IContext context,
		java.lang.String _handle
	)
	{
		super(context);
		this.handle = _handle;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (handle != null) {
			NanoProfiler nanoProfiler = NanoProfiler.getProfilerMap().get(handle);
			if (nanoProfiler != null) {
				NanoProfiler.getProfilerMap().remove(handle);
			}
		}
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "StopNanoProfiler";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
