// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package nanoprofiler.actions;

import java.util.Map;
import com.mendix.systemwideinterfaces.core.IContext;
import nanoprofiler.implementation.NanoProfiler;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Profile point name, elapsed time and number of calls.
 * If an empty string (not empty but empty string) is specified as the handle and there is only one profiler started, it will be recorded in that profiler.
 * This Action took only 19 microseconds each time measured with Mendix 8.12.7 on i7-10610U laptop. As a reference, an empty Java Action took 16 microseconds on the same measurement.
 */
public class TickNanoProfiler extends UserAction<java.lang.Void>
{
	private final java.lang.String handle;
	private final java.lang.String pointName;

	public TickNanoProfiler(
		IContext context,
		java.lang.String _handle,
		java.lang.String _pointName
	)
	{
		super(context);
		this.handle = _handle;
		this.pointName = _pointName;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (handle != null) {
			Map<String, NanoProfiler> profilerMap = NanoProfiler.getProfilerMap();
			NanoProfiler nanoProfiler = profilerMap.get(handle);
			if (nanoProfiler != null) {
				nanoProfiler.tick(getContext(), pointName);
			} else if ("".equals(handle) && profilerMap.size() == 1) {
				nanoProfiler = profilerMap.values().iterator().next();
				nanoProfiler.tick(getContext(), pointName);
			}
		}
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "TickNanoProfiler";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
