// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twowaysqlmocker.actions;

import java.util.List;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import twowaysqlmocker.implementation.ExcelReader;

/**
 * This Action exposes the functionality of the TwoWaySQL '$$MOCK_EXCEL$$' directive to load Excel files.
 * It can be used in conjunction with the '$$MOCK_MICROFLOW$$' directive to load specific Excel files based on conditional logic within a mock Microflow.
 */
public class ReadExcelFromFile extends UserAction<java.util.List<IMendixObject>>
{
	private final java.lang.String ExcelFilePath;
	private final java.lang.String RecordEntityType;
	private final java.lang.String SheetName;
	private final java.lang.String TimeZoneId;

	public ReadExcelFromFile(
		IContext context,
		java.lang.String _excelFilePath,
		java.lang.String _recordEntityType,
		java.lang.String _sheetName,
		java.lang.String _timeZoneId
	)
	{
		super(context);
		this.ExcelFilePath = _excelFilePath;
		this.RecordEntityType = _recordEntityType;
		this.SheetName = _sheetName;
		this.TimeZoneId = _timeZoneId;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		List<IMendixObject> resultList = ExcelReader.readExcelFromFile(getContext(), ExcelFilePath, RecordEntityType, SheetName, TimeZoneId);
		return resultList;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ReadExcelFromFile";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
