// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package profileservice.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the ProfileService module
	public static profileservice.proxies.UserProfile getUserProfile(IContext context, java.lang.String _openID, java.lang.String _environmentUUID, java.lang.String _environmentPassword)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("OpenID", _openID);
		params.put("EnvironmentUUID", _environmentUUID);
		params.put("EnvironmentPassword", _environmentPassword);
		IMendixObject result = (IMendixObject)Core.microflowCall("ProfileService.GetUserProfile").withParams(params).execute(context);
		return result == null ? null : profileservice.proxies.UserProfile.initialize(context, result);
	}
}